package pe.gob.miraflores.mobile.domain.mapaincidencias;

public class GeometriaLinea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_INICIDENCIA_LINEA.ID_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    private Integer idLinea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_INICIDENCIA_LINEA.POINT_INI
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    private String pointIni;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_INICIDENCIA_LINEA.POINT_FIN
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    private String pointFin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_INICIDENCIA_LINEA.DES_CALLE
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    private String desCalle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_1
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    private String intercepcion1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_2
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    private String intercepcion2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_INICIDENCIA_LINEA.ID_INCIDENCIA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    private Integer idIncidencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_INICIDENCIA_LINEA.DIR_CARDINAL
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    private String dirCardinal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_INICIDENCIA_LINEA.ID_LINEA
     *
     * @return the value of GEO_MAP_INICIDENCIA_LINEA.ID_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public Integer getIdLinea() {
        return idLinea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_INICIDENCIA_LINEA.ID_LINEA
     *
     * @param idLinea the value for GEO_MAP_INICIDENCIA_LINEA.ID_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public void setIdLinea(Integer idLinea) {
        this.idLinea = idLinea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_INICIDENCIA_LINEA.POINT_INI
     *
     * @return the value of GEO_MAP_INICIDENCIA_LINEA.POINT_INI
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public String getPointIni() {
        return pointIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_INICIDENCIA_LINEA.POINT_INI
     *
     * @param pointIni the value for GEO_MAP_INICIDENCIA_LINEA.POINT_INI
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public void setPointIni(String pointIni) {
        this.pointIni = pointIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_INICIDENCIA_LINEA.POINT_FIN
     *
     * @return the value of GEO_MAP_INICIDENCIA_LINEA.POINT_FIN
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public String getPointFin() {
        return pointFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_INICIDENCIA_LINEA.POINT_FIN
     *
     * @param pointFin the value for GEO_MAP_INICIDENCIA_LINEA.POINT_FIN
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public void setPointFin(String pointFin) {
        this.pointFin = pointFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_INICIDENCIA_LINEA.DES_CALLE
     *
     * @return the value of GEO_MAP_INICIDENCIA_LINEA.DES_CALLE
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public String getDesCalle() {
        return desCalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_INICIDENCIA_LINEA.DES_CALLE
     *
     * @param desCalle the value for GEO_MAP_INICIDENCIA_LINEA.DES_CALLE
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public void setDesCalle(String desCalle) {
        this.desCalle = desCalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_1
     *
     * @return the value of GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_1
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public String getIntercepcion1() {
        return intercepcion1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_1
     *
     * @param intercepcion1 the value for GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_1
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public void setIntercepcion1(String intercepcion1) {
        this.intercepcion1 = intercepcion1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_2
     *
     * @return the value of GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_2
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public String getIntercepcion2() {
        return intercepcion2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_2
     *
     * @param intercepcion2 the value for GEO_MAP_INICIDENCIA_LINEA.INTERCEPCION_2
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public void setIntercepcion2(String intercepcion2) {
        this.intercepcion2 = intercepcion2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_INICIDENCIA_LINEA.ID_INCIDENCIA
     *
     * @return the value of GEO_MAP_INICIDENCIA_LINEA.ID_INCIDENCIA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public Integer getIdIncidencia() {
        return idIncidencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_INICIDENCIA_LINEA.ID_INCIDENCIA
     *
     * @param idIncidencia the value for GEO_MAP_INICIDENCIA_LINEA.ID_INCIDENCIA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public void setIdIncidencia(Integer idIncidencia) {
        this.idIncidencia = idIncidencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_INICIDENCIA_LINEA.DIR_CARDINAL
     *
     * @return the value of GEO_MAP_INICIDENCIA_LINEA.DIR_CARDINAL
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public String getDirCardinal() {
        return dirCardinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_INICIDENCIA_LINEA.DIR_CARDINAL
     *
     * @param dirCardinal the value for GEO_MAP_INICIDENCIA_LINEA.DIR_CARDINAL
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    public void setDirCardinal(String dirCardinal) {
        this.dirCardinal = dirCardinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GeometriaLinea other = (GeometriaLinea) that;
        return (this.getIdLinea() == null ? other.getIdLinea() == null : this.getIdLinea().equals(other.getIdLinea()))
            && (this.getPointIni() == null ? other.getPointIni() == null : this.getPointIni().equals(other.getPointIni()))
            && (this.getPointFin() == null ? other.getPointFin() == null : this.getPointFin().equals(other.getPointFin()))
            && (this.getDesCalle() == null ? other.getDesCalle() == null : this.getDesCalle().equals(other.getDesCalle()))
            && (this.getIntercepcion1() == null ? other.getIntercepcion1() == null : this.getIntercepcion1().equals(other.getIntercepcion1()))
            && (this.getIntercepcion2() == null ? other.getIntercepcion2() == null : this.getIntercepcion2().equals(other.getIntercepcion2()))
            && (this.getIdIncidencia() == null ? other.getIdIncidencia() == null : this.getIdIncidencia().equals(other.getIdIncidencia()))
            && (this.getDirCardinal() == null ? other.getDirCardinal() == null : this.getDirCardinal().equals(other.getDirCardinal()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdLinea() == null) ? 0 : getIdLinea().hashCode());
        result = prime * result + ((getPointIni() == null) ? 0 : getPointIni().hashCode());
        result = prime * result + ((getPointFin() == null) ? 0 : getPointFin().hashCode());
        result = prime * result + ((getDesCalle() == null) ? 0 : getDesCalle().hashCode());
        result = prime * result + ((getIntercepcion1() == null) ? 0 : getIntercepcion1().hashCode());
        result = prime * result + ((getIntercepcion2() == null) ? 0 : getIntercepcion2().hashCode());
        result = prime * result + ((getIdIncidencia() == null) ? 0 : getIdIncidencia().hashCode());
        result = prime * result + ((getDirCardinal() == null) ? 0 : getDirCardinal().hashCode());
        return result;
    }
}