package pe.gob.miraflores.mobile.domain.mapaincidencias;

public class MapaIncidenciasGeometria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEOMGEOMETRIA.IDGEOREFERENCIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    private Integer idgeoreferencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEOMGEOMETRIA.IDETIPOGEOMETRIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    private Integer idetipogeometria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEOMGEOMETRIA.GEOMETRIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    private String geometria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEOMGEOMETRIA.IDECODVALOR
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    private Integer idecodvalor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEOMGEOMETRIA.IDECODIDENT
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    private Integer idecodident;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEOMGEOMETRIA.INDESTADO
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    private Integer indestado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEOMGEOMETRIA.DESDIRECCION
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    private String desdireccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEOMGEOMETRIA.ORDEN
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    private Integer orden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEOMGEOMETRIA.IDGEOREFERENCIA
     *
     * @return the value of GEOMGEOMETRIA.IDGEOREFERENCIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public Integer getIdgeoreferencia() {
        return idgeoreferencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEOMGEOMETRIA.IDGEOREFERENCIA
     *
     * @param idgeoreferencia the value for GEOMGEOMETRIA.IDGEOREFERENCIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public void setIdgeoreferencia(Integer idgeoreferencia) {
        this.idgeoreferencia = idgeoreferencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEOMGEOMETRIA.IDETIPOGEOMETRIA
     *
     * @return the value of GEOMGEOMETRIA.IDETIPOGEOMETRIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public Integer getIdetipogeometria() {
        return idetipogeometria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEOMGEOMETRIA.IDETIPOGEOMETRIA
     *
     * @param idetipogeometria the value for GEOMGEOMETRIA.IDETIPOGEOMETRIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public void setIdetipogeometria(Integer idetipogeometria) {
        this.idetipogeometria = idetipogeometria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEOMGEOMETRIA.GEOMETRIA
     *
     * @return the value of GEOMGEOMETRIA.GEOMETRIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public String getGeometria() {
        return geometria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEOMGEOMETRIA.GEOMETRIA
     *
     * @param geometria the value for GEOMGEOMETRIA.GEOMETRIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public void setGeometria(String geometria) {
        this.geometria = geometria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEOMGEOMETRIA.IDECODVALOR
     *
     * @return the value of GEOMGEOMETRIA.IDECODVALOR
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public Integer getIdecodvalor() {
        return idecodvalor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEOMGEOMETRIA.IDECODVALOR
     *
     * @param idecodvalor the value for GEOMGEOMETRIA.IDECODVALOR
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public void setIdecodvalor(Integer idecodvalor) {
        this.idecodvalor = idecodvalor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEOMGEOMETRIA.IDECODIDENT
     *
     * @return the value of GEOMGEOMETRIA.IDECODIDENT
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public Integer getIdecodident() {
        return idecodident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEOMGEOMETRIA.IDECODIDENT
     *
     * @param idecodident the value for GEOMGEOMETRIA.IDECODIDENT
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public void setIdecodident(Integer idecodident) {
        this.idecodident = idecodident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEOMGEOMETRIA.INDESTADO
     *
     * @return the value of GEOMGEOMETRIA.INDESTADO
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public Integer getIndestado() {
        return indestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEOMGEOMETRIA.INDESTADO
     *
     * @param indestado the value for GEOMGEOMETRIA.INDESTADO
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public void setIndestado(Integer indestado) {
        this.indestado = indestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEOMGEOMETRIA.DESDIRECCION
     *
     * @return the value of GEOMGEOMETRIA.DESDIRECCION
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public String getDesdireccion() {
        return desdireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEOMGEOMETRIA.DESDIRECCION
     *
     * @param desdireccion the value for GEOMGEOMETRIA.DESDIRECCION
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public void setDesdireccion(String desdireccion) {
        this.desdireccion = desdireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEOMGEOMETRIA.ORDEN
     *
     * @return the value of GEOMGEOMETRIA.ORDEN
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public Integer getOrden() {
        return orden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEOMGEOMETRIA.ORDEN
     *
     * @param orden the value for GEOMGEOMETRIA.ORDEN
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEOMGEOMETRIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MapaIncidenciasGeometria other = (MapaIncidenciasGeometria) that;
        return (this.getIdgeoreferencia() == null ? other.getIdgeoreferencia() == null : this.getIdgeoreferencia().equals(other.getIdgeoreferencia()))
            && (this.getIdetipogeometria() == null ? other.getIdetipogeometria() == null : this.getIdetipogeometria().equals(other.getIdetipogeometria()))
            && (this.getGeometria() == null ? other.getGeometria() == null : this.getGeometria().equals(other.getGeometria()))
            && (this.getIdecodvalor() == null ? other.getIdecodvalor() == null : this.getIdecodvalor().equals(other.getIdecodvalor()))
            && (this.getIdecodident() == null ? other.getIdecodident() == null : this.getIdecodident().equals(other.getIdecodident()))
            && (this.getIndestado() == null ? other.getIndestado() == null : this.getIndestado().equals(other.getIndestado()))
            && (this.getDesdireccion() == null ? other.getDesdireccion() == null : this.getDesdireccion().equals(other.getDesdireccion()))
            && (this.getOrden() == null ? other.getOrden() == null : this.getOrden().equals(other.getOrden()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEOMGEOMETRIA
     *
     * @mbggenerated Fri Oct 23 15:41:13 COT 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdgeoreferencia() == null) ? 0 : getIdgeoreferencia().hashCode());
        result = prime * result + ((getIdetipogeometria() == null) ? 0 : getIdetipogeometria().hashCode());
        result = prime * result + ((getGeometria() == null) ? 0 : getGeometria().hashCode());
        result = prime * result + ((getIdecodvalor() == null) ? 0 : getIdecodvalor().hashCode());
        result = prime * result + ((getIdecodident() == null) ? 0 : getIdecodident().hashCode());
        result = prime * result + ((getIndestado() == null) ? 0 : getIndestado().hashCode());
        result = prime * result + ((getDesdireccion() == null) ? 0 : getDesdireccion().hashCode());
        result = prime * result + ((getOrden() == null) ? 0 : getOrden().hashCode());
        return result;
    }
}