package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MapaIncidenciasRegistroCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public MapaIncidenciasRegistroCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIncidenciaIsNull() {
			addCriterion("ID_INCIDENCIA is null");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaIsNotNull() {
			addCriterion("ID_INCIDENCIA is not null");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaEqualTo(Integer value) {
			addCriterion("ID_INCIDENCIA =", value, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaNotEqualTo(Integer value) {
			addCriterion("ID_INCIDENCIA <>", value, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaGreaterThan(Integer value) {
			addCriterion("ID_INCIDENCIA >", value, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_INCIDENCIA >=", value, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaLessThan(Integer value) {
			addCriterion("ID_INCIDENCIA <", value, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaLessThanOrEqualTo(Integer value) {
			addCriterion("ID_INCIDENCIA <=", value, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaIn(List<Integer> values) {
			addCriterion("ID_INCIDENCIA in", values, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaNotIn(List<Integer> values) {
			addCriterion("ID_INCIDENCIA not in", values, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaBetween(Integer value1, Integer value2) {
			addCriterion("ID_INCIDENCIA between", value1, value2, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdIncidenciaNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_INCIDENCIA not between", value1, value2, "idIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdEventoIsNull() {
			addCriterion("ID_EVENTO is null");
			return (Criteria) this;
		}

		public Criteria andIdEventoIsNotNull() {
			addCriterion("ID_EVENTO is not null");
			return (Criteria) this;
		}

		public Criteria andIdEventoEqualTo(Integer value) {
			addCriterion("ID_EVENTO =", value, "idEvento");
			return (Criteria) this;
		}

		public Criteria andIdEventoNotEqualTo(Integer value) {
			addCriterion("ID_EVENTO <>", value, "idEvento");
			return (Criteria) this;
		}

		public Criteria andIdEventoGreaterThan(Integer value) {
			addCriterion("ID_EVENTO >", value, "idEvento");
			return (Criteria) this;
		}

		public Criteria andIdEventoGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_EVENTO >=", value, "idEvento");
			return (Criteria) this;
		}

		public Criteria andIdEventoLessThan(Integer value) {
			addCriterion("ID_EVENTO <", value, "idEvento");
			return (Criteria) this;
		}

		public Criteria andIdEventoLessThanOrEqualTo(Integer value) {
			addCriterion("ID_EVENTO <=", value, "idEvento");
			return (Criteria) this;
		}

		public Criteria andIdEventoIn(List<Integer> values) {
			addCriterion("ID_EVENTO in", values, "idEvento");
			return (Criteria) this;
		}

		public Criteria andIdEventoNotIn(List<Integer> values) {
			addCriterion("ID_EVENTO not in", values, "idEvento");
			return (Criteria) this;
		}

		public Criteria andIdEventoBetween(Integer value1, Integer value2) {
			addCriterion("ID_EVENTO between", value1, value2, "idEvento");
			return (Criteria) this;
		}

		public Criteria andIdEventoNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_EVENTO not between", value1, value2, "idEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoIsNull() {
			addCriterion("TIPO_EVENTO is null");
			return (Criteria) this;
		}

		public Criteria andTipoEventoIsNotNull() {
			addCriterion("TIPO_EVENTO is not null");
			return (Criteria) this;
		}

		public Criteria andTipoEventoEqualTo(Integer value) {
			addCriterion("TIPO_EVENTO =", value, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoNotEqualTo(Integer value) {
			addCriterion("TIPO_EVENTO <>", value, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoGreaterThan(Integer value) {
			addCriterion("TIPO_EVENTO >", value, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoGreaterThanOrEqualTo(Integer value) {
			addCriterion("TIPO_EVENTO >=", value, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoLessThan(Integer value) {
			addCriterion("TIPO_EVENTO <", value, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoLessThanOrEqualTo(Integer value) {
			addCriterion("TIPO_EVENTO <=", value, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoIn(List<Integer> values) {
			addCriterion("TIPO_EVENTO in", values, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoNotIn(List<Integer> values) {
			addCriterion("TIPO_EVENTO not in", values, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoBetween(Integer value1, Integer value2) {
			addCriterion("TIPO_EVENTO between", value1, value2, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andTipoEventoNotBetween(Integer value1, Integer value2) {
			addCriterion("TIPO_EVENTO not between", value1, value2, "tipoEvento");
			return (Criteria) this;
		}

		public Criteria andSubTipoIsNull() {
			addCriterion("SUB_TIPO is null");
			return (Criteria) this;
		}

		public Criteria andSubTipoIsNotNull() {
			addCriterion("SUB_TIPO is not null");
			return (Criteria) this;
		}

		public Criteria andSubTipoEqualTo(Integer value) {
			addCriterion("SUB_TIPO =", value, "subTipo");
			return (Criteria) this;
		}

		public Criteria andSubTipoNotEqualTo(Integer value) {
			addCriterion("SUB_TIPO <>", value, "subTipo");
			return (Criteria) this;
		}

		public Criteria andSubTipoGreaterThan(Integer value) {
			addCriterion("SUB_TIPO >", value, "subTipo");
			return (Criteria) this;
		}

		public Criteria andSubTipoGreaterThanOrEqualTo(Integer value) {
			addCriterion("SUB_TIPO >=", value, "subTipo");
			return (Criteria) this;
		}

		public Criteria andSubTipoLessThan(Integer value) {
			addCriterion("SUB_TIPO <", value, "subTipo");
			return (Criteria) this;
		}

		public Criteria andSubTipoLessThanOrEqualTo(Integer value) {
			addCriterion("SUB_TIPO <=", value, "subTipo");
			return (Criteria) this;
		}

		public Criteria andSubTipoIn(List<Integer> values) {
			addCriterion("SUB_TIPO in", values, "subTipo");
			return (Criteria) this;
		}

		public Criteria andSubTipoNotIn(List<Integer> values) {
			addCriterion("SUB_TIPO not in", values, "subTipo");
			return (Criteria) this;
		}

		public Criteria andSubTipoBetween(Integer value1, Integer value2) {
			addCriterion("SUB_TIPO between", value1, value2, "subTipo");
			return (Criteria) this;
		}

		public Criteria andSubTipoNotBetween(Integer value1, Integer value2) {
			addCriterion("SUB_TIPO not between", value1, value2, "subTipo");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioIsNull() {
			addCriterion("FEC_HORA_INICIO is null");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioIsNotNull() {
			addCriterion("FEC_HORA_INICIO is not null");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioEqualTo(Date value) {
			addCriterion("FEC_HORA_INICIO =", value, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioNotEqualTo(Date value) {
			addCriterion("FEC_HORA_INICIO <>", value, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioGreaterThan(Date value) {
			addCriterion("FEC_HORA_INICIO >", value, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioGreaterThanOrEqualTo(Date value) {
			addCriterion("FEC_HORA_INICIO >=", value, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioLessThan(Date value) {
			addCriterion("FEC_HORA_INICIO <", value, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioLessThanOrEqualTo(Date value) {
			addCriterion("FEC_HORA_INICIO <=", value, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioIn(List<Date> values) {
			addCriterion("FEC_HORA_INICIO in", values, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioNotIn(List<Date> values) {
			addCriterion("FEC_HORA_INICIO not in", values, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioBetween(Date value1, Date value2) {
			addCriterion("FEC_HORA_INICIO between", value1, value2, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraInicioNotBetween(Date value1, Date value2) {
			addCriterion("FEC_HORA_INICIO not between", value1, value2, "fecHoraInicio");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinIsNull() {
			addCriterion("FEC_HORA_FIN is null");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinIsNotNull() {
			addCriterion("FEC_HORA_FIN is not null");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinEqualTo(Date value) {
			addCriterion("FEC_HORA_FIN =", value, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinNotEqualTo(Date value) {
			addCriterion("FEC_HORA_FIN <>", value, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinGreaterThan(Date value) {
			addCriterion("FEC_HORA_FIN >", value, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinGreaterThanOrEqualTo(Date value) {
			addCriterion("FEC_HORA_FIN >=", value, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinLessThan(Date value) {
			addCriterion("FEC_HORA_FIN <", value, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinLessThanOrEqualTo(Date value) {
			addCriterion("FEC_HORA_FIN <=", value, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinIn(List<Date> values) {
			addCriterion("FEC_HORA_FIN in", values, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinNotIn(List<Date> values) {
			addCriterion("FEC_HORA_FIN not in", values, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinBetween(Date value1, Date value2) {
			addCriterion("FEC_HORA_FIN between", value1, value2, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andFecHoraFinNotBetween(Date value1, Date value2) {
			addCriterion("FEC_HORA_FIN not between", value1, value2, "fecHoraFin");
			return (Criteria) this;
		}

		public Criteria andDescripcionIsNull() {
			addCriterion("DESCRIPCION is null");
			return (Criteria) this;
		}

		public Criteria andDescripcionIsNotNull() {
			addCriterion("DESCRIPCION is not null");
			return (Criteria) this;
		}

		public Criteria andDescripcionEqualTo(String value) {
			addCriterion("DESCRIPCION =", value, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionNotEqualTo(String value) {
			addCriterion("DESCRIPCION <>", value, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionGreaterThan(String value) {
			addCriterion("DESCRIPCION >", value, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPCION >=", value, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionLessThan(String value) {
			addCriterion("DESCRIPCION <", value, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPCION <=", value, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionLike(String value) {
			addCriterion("DESCRIPCION like", value, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionNotLike(String value) {
			addCriterion("DESCRIPCION not like", value, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionIn(List<String> values) {
			addCriterion("DESCRIPCION in", values, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionNotIn(List<String> values) {
			addCriterion("DESCRIPCION not in", values, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionBetween(String value1, String value2) {
			addCriterion("DESCRIPCION between", value1, value2, "descripcion");
			return (Criteria) this;
		}

		public Criteria andDescripcionNotBetween(String value1, String value2) {
			addCriterion("DESCRIPCION not between", value1, value2, "descripcion");
			return (Criteria) this;
		}

		public Criteria andSeveridadIsNull() {
			addCriterion("SEVERIDAD is null");
			return (Criteria) this;
		}

		public Criteria andSeveridadIsNotNull() {
			addCriterion("SEVERIDAD is not null");
			return (Criteria) this;
		}

		public Criteria andSeveridadEqualTo(String value) {
			addCriterion("SEVERIDAD =", value, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadNotEqualTo(String value) {
			addCriterion("SEVERIDAD <>", value, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadGreaterThan(String value) {
			addCriterion("SEVERIDAD >", value, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadGreaterThanOrEqualTo(String value) {
			addCriterion("SEVERIDAD >=", value, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadLessThan(String value) {
			addCriterion("SEVERIDAD <", value, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadLessThanOrEqualTo(String value) {
			addCriterion("SEVERIDAD <=", value, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadLike(String value) {
			addCriterion("SEVERIDAD like", value, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadNotLike(String value) {
			addCriterion("SEVERIDAD not like", value, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadIn(List<String> values) {
			addCriterion("SEVERIDAD in", values, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadNotIn(List<String> values) {
			addCriterion("SEVERIDAD not in", values, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadBetween(String value1, String value2) {
			addCriterion("SEVERIDAD between", value1, value2, "severidad");
			return (Criteria) this;
		}

		public Criteria andSeveridadNotBetween(String value1, String value2) {
			addCriterion("SEVERIDAD not between", value1, value2, "severidad");
			return (Criteria) this;
		}

		public Criteria andCalleIsNull() {
			addCriterion("CALLE is null");
			return (Criteria) this;
		}

		public Criteria andCalleIsNotNull() {
			addCriterion("CALLE is not null");
			return (Criteria) this;
		}

		public Criteria andCalleEqualTo(String value) {
			addCriterion("CALLE =", value, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleNotEqualTo(String value) {
			addCriterion("CALLE <>", value, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleGreaterThan(String value) {
			addCriterion("CALLE >", value, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleGreaterThanOrEqualTo(String value) {
			addCriterion("CALLE >=", value, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleLessThan(String value) {
			addCriterion("CALLE <", value, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleLessThanOrEqualTo(String value) {
			addCriterion("CALLE <=", value, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleLike(String value) {
			addCriterion("CALLE like", value, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleNotLike(String value) {
			addCriterion("CALLE not like", value, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleIn(List<String> values) {
			addCriterion("CALLE in", values, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleNotIn(List<String> values) {
			addCriterion("CALLE not in", values, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleBetween(String value1, String value2) {
			addCriterion("CALLE between", value1, value2, "calle");
			return (Criteria) this;
		}

		public Criteria andCalleNotBetween(String value1, String value2) {
			addCriterion("CALLE not between", value1, value2, "calle");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionIsNull() {
			addCriterion("TIPO_DIRECCION is null");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionIsNotNull() {
			addCriterion("TIPO_DIRECCION is not null");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionEqualTo(Integer value) {
			addCriterion("TIPO_DIRECCION =", value, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionNotEqualTo(Integer value) {
			addCriterion("TIPO_DIRECCION <>", value, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionGreaterThan(Integer value) {
			addCriterion("TIPO_DIRECCION >", value, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionGreaterThanOrEqualTo(Integer value) {
			addCriterion("TIPO_DIRECCION >=", value, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionLessThan(Integer value) {
			addCriterion("TIPO_DIRECCION <", value, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionLessThanOrEqualTo(Integer value) {
			addCriterion("TIPO_DIRECCION <=", value, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionIn(List<Integer> values) {
			addCriterion("TIPO_DIRECCION in", values, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionNotIn(List<Integer> values) {
			addCriterion("TIPO_DIRECCION not in", values, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionBetween(Integer value1, Integer value2) {
			addCriterion("TIPO_DIRECCION between", value1, value2, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andTipoDireccionNotBetween(Integer value1, Integer value2) {
			addCriterion("TIPO_DIRECCION not between", value1, value2, "tipoDireccion");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalIsNull() {
			addCriterion("DIRECCION_FINAL is null");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalIsNotNull() {
			addCriterion("DIRECCION_FINAL is not null");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalEqualTo(String value) {
			addCriterion("DIRECCION_FINAL =", value, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalNotEqualTo(String value) {
			addCriterion("DIRECCION_FINAL <>", value, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalGreaterThan(String value) {
			addCriterion("DIRECCION_FINAL >", value, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalGreaterThanOrEqualTo(String value) {
			addCriterion("DIRECCION_FINAL >=", value, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalLessThan(String value) {
			addCriterion("DIRECCION_FINAL <", value, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalLessThanOrEqualTo(String value) {
			addCriterion("DIRECCION_FINAL <=", value, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalLike(String value) {
			addCriterion("DIRECCION_FINAL like", value, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalNotLike(String value) {
			addCriterion("DIRECCION_FINAL not like", value, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalIn(List<String> values) {
			addCriterion("DIRECCION_FINAL in", values, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalNotIn(List<String> values) {
			addCriterion("DIRECCION_FINAL not in", values, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalBetween(String value1, String value2) {
			addCriterion("DIRECCION_FINAL between", value1, value2, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalNotBetween(String value1, String value2) {
			addCriterion("DIRECCION_FINAL not between", value1, value2, "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioIsNull() {
			addCriterion("NOMBRE_CALLE_INICIO is null");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioIsNotNull() {
			addCriterion("NOMBRE_CALLE_INICIO is not null");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioEqualTo(String value) {
			addCriterion("NOMBRE_CALLE_INICIO =", value, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioNotEqualTo(String value) {
			addCriterion("NOMBRE_CALLE_INICIO <>", value, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioGreaterThan(String value) {
			addCriterion("NOMBRE_CALLE_INICIO >", value, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE_CALLE_INICIO >=", value, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioLessThan(String value) {
			addCriterion("NOMBRE_CALLE_INICIO <", value, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE_CALLE_INICIO <=", value, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioLike(String value) {
			addCriterion("NOMBRE_CALLE_INICIO like", value, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioNotLike(String value) {
			addCriterion("NOMBRE_CALLE_INICIO not like", value, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioIn(List<String> values) {
			addCriterion("NOMBRE_CALLE_INICIO in", values, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioNotIn(List<String> values) {
			addCriterion("NOMBRE_CALLE_INICIO not in", values, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioBetween(String value1, String value2) {
			addCriterion("NOMBRE_CALLE_INICIO between", value1, value2, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioNotBetween(String value1, String value2) {
			addCriterion("NOMBRE_CALLE_INICIO not between", value1, value2, "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinIsNull() {
			addCriterion("NOMBRE_CALLE_FIN is null");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinIsNotNull() {
			addCriterion("NOMBRE_CALLE_FIN is not null");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinEqualTo(String value) {
			addCriterion("NOMBRE_CALLE_FIN =", value, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinNotEqualTo(String value) {
			addCriterion("NOMBRE_CALLE_FIN <>", value, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinGreaterThan(String value) {
			addCriterion("NOMBRE_CALLE_FIN >", value, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE_CALLE_FIN >=", value, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinLessThan(String value) {
			addCriterion("NOMBRE_CALLE_FIN <", value, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE_CALLE_FIN <=", value, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinLike(String value) {
			addCriterion("NOMBRE_CALLE_FIN like", value, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinNotLike(String value) {
			addCriterion("NOMBRE_CALLE_FIN not like", value, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinIn(List<String> values) {
			addCriterion("NOMBRE_CALLE_FIN in", values, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinNotIn(List<String> values) {
			addCriterion("NOMBRE_CALLE_FIN not in", values, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinBetween(String value1, String value2) {
			addCriterion("NOMBRE_CALLE_FIN between", value1, value2, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinNotBetween(String value1, String value2) {
			addCriterion("NOMBRE_CALLE_FIN not between", value1, value2, "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andFecRegistraIsNull() {
			addCriterion("FEC_REGISTRA is null");
			return (Criteria) this;
		}

		public Criteria andFecRegistraIsNotNull() {
			addCriterion("FEC_REGISTRA is not null");
			return (Criteria) this;
		}

		public Criteria andFecRegistraEqualTo(Date value) {
			addCriterion("FEC_REGISTRA =", value, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecRegistraNotEqualTo(Date value) {
			addCriterion("FEC_REGISTRA <>", value, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecRegistraGreaterThan(Date value) {
			addCriterion("FEC_REGISTRA >", value, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecRegistraGreaterThanOrEqualTo(Date value) {
			addCriterion("FEC_REGISTRA >=", value, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecRegistraLessThan(Date value) {
			addCriterion("FEC_REGISTRA <", value, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecRegistraLessThanOrEqualTo(Date value) {
			addCriterion("FEC_REGISTRA <=", value, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecRegistraIn(List<Date> values) {
			addCriterion("FEC_REGISTRA in", values, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecRegistraNotIn(List<Date> values) {
			addCriterion("FEC_REGISTRA not in", values, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecRegistraBetween(Date value1, Date value2) {
			addCriterion("FEC_REGISTRA between", value1, value2, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecRegistraNotBetween(Date value1, Date value2) {
			addCriterion("FEC_REGISTRA not between", value1, value2, "fecRegistra");
			return (Criteria) this;
		}

		public Criteria andFecModificaIsNull() {
			addCriterion("FEC_MODIFICA is null");
			return (Criteria) this;
		}

		public Criteria andFecModificaIsNotNull() {
			addCriterion("FEC_MODIFICA is not null");
			return (Criteria) this;
		}

		public Criteria andFecModificaEqualTo(Date value) {
			addCriterion("FEC_MODIFICA =", value, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andFecModificaNotEqualTo(Date value) {
			addCriterion("FEC_MODIFICA <>", value, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andFecModificaGreaterThan(Date value) {
			addCriterion("FEC_MODIFICA >", value, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andFecModificaGreaterThanOrEqualTo(Date value) {
			addCriterion("FEC_MODIFICA >=", value, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andFecModificaLessThan(Date value) {
			addCriterion("FEC_MODIFICA <", value, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andFecModificaLessThanOrEqualTo(Date value) {
			addCriterion("FEC_MODIFICA <=", value, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andFecModificaIn(List<Date> values) {
			addCriterion("FEC_MODIFICA in", values, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andFecModificaNotIn(List<Date> values) {
			addCriterion("FEC_MODIFICA not in", values, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andFecModificaBetween(Date value1, Date value2) {
			addCriterion("FEC_MODIFICA between", value1, value2, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andFecModificaNotBetween(Date value1, Date value2) {
			addCriterion("FEC_MODIFICA not between", value1, value2, "fecModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraIsNull() {
			addCriterion("DES_USU_REGISTRA is null");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraIsNotNull() {
			addCriterion("DES_USU_REGISTRA is not null");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraEqualTo(String value) {
			addCriterion("DES_USU_REGISTRA =", value, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraNotEqualTo(String value) {
			addCriterion("DES_USU_REGISTRA <>", value, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraGreaterThan(String value) {
			addCriterion("DES_USU_REGISTRA >", value, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraGreaterThanOrEqualTo(String value) {
			addCriterion("DES_USU_REGISTRA >=", value, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraLessThan(String value) {
			addCriterion("DES_USU_REGISTRA <", value, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraLessThanOrEqualTo(String value) {
			addCriterion("DES_USU_REGISTRA <=", value, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraLike(String value) {
			addCriterion("DES_USU_REGISTRA like", value, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraNotLike(String value) {
			addCriterion("DES_USU_REGISTRA not like", value, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraIn(List<String> values) {
			addCriterion("DES_USU_REGISTRA in", values, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraNotIn(List<String> values) {
			addCriterion("DES_USU_REGISTRA not in", values, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraBetween(String value1, String value2) {
			addCriterion("DES_USU_REGISTRA between", value1, value2, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraNotBetween(String value1, String value2) {
			addCriterion("DES_USU_REGISTRA not between", value1, value2, "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaIsNull() {
			addCriterion("DES_USU_MODIFICA is null");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaIsNotNull() {
			addCriterion("DES_USU_MODIFICA is not null");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaEqualTo(String value) {
			addCriterion("DES_USU_MODIFICA =", value, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaNotEqualTo(String value) {
			addCriterion("DES_USU_MODIFICA <>", value, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaGreaterThan(String value) {
			addCriterion("DES_USU_MODIFICA >", value, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaGreaterThanOrEqualTo(String value) {
			addCriterion("DES_USU_MODIFICA >=", value, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaLessThan(String value) {
			addCriterion("DES_USU_MODIFICA <", value, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaLessThanOrEqualTo(String value) {
			addCriterion("DES_USU_MODIFICA <=", value, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaLike(String value) {
			addCriterion("DES_USU_MODIFICA like", value, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaNotLike(String value) {
			addCriterion("DES_USU_MODIFICA not like", value, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaIn(List<String> values) {
			addCriterion("DES_USU_MODIFICA in", values, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaNotIn(List<String> values) {
			addCriterion("DES_USU_MODIFICA not in", values, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaBetween(String value1, String value2) {
			addCriterion("DES_USU_MODIFICA between", value1, value2, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaNotBetween(String value1, String value2) {
			addCriterion("DES_USU_MODIFICA not between", value1, value2, "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraIsNull() {
			addCriterion("DES_IP_REGISTRA is null");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraIsNotNull() {
			addCriterion("DES_IP_REGISTRA is not null");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraEqualTo(String value) {
			addCriterion("DES_IP_REGISTRA =", value, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraNotEqualTo(String value) {
			addCriterion("DES_IP_REGISTRA <>", value, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraGreaterThan(String value) {
			addCriterion("DES_IP_REGISTRA >", value, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraGreaterThanOrEqualTo(String value) {
			addCriterion("DES_IP_REGISTRA >=", value, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraLessThan(String value) {
			addCriterion("DES_IP_REGISTRA <", value, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraLessThanOrEqualTo(String value) {
			addCriterion("DES_IP_REGISTRA <=", value, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraLike(String value) {
			addCriterion("DES_IP_REGISTRA like", value, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraNotLike(String value) {
			addCriterion("DES_IP_REGISTRA not like", value, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraIn(List<String> values) {
			addCriterion("DES_IP_REGISTRA in", values, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraNotIn(List<String> values) {
			addCriterion("DES_IP_REGISTRA not in", values, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraBetween(String value1, String value2) {
			addCriterion("DES_IP_REGISTRA between", value1, value2, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraNotBetween(String value1, String value2) {
			addCriterion("DES_IP_REGISTRA not between", value1, value2, "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaIsNull() {
			addCriterion("DES_IP_MODIFICA is null");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaIsNotNull() {
			addCriterion("DES_IP_MODIFICA is not null");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaEqualTo(String value) {
			addCriterion("DES_IP_MODIFICA =", value, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaNotEqualTo(String value) {
			addCriterion("DES_IP_MODIFICA <>", value, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaGreaterThan(String value) {
			addCriterion("DES_IP_MODIFICA >", value, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaGreaterThanOrEqualTo(String value) {
			addCriterion("DES_IP_MODIFICA >=", value, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaLessThan(String value) {
			addCriterion("DES_IP_MODIFICA <", value, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaLessThanOrEqualTo(String value) {
			addCriterion("DES_IP_MODIFICA <=", value, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaLike(String value) {
			addCriterion("DES_IP_MODIFICA like", value, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaNotLike(String value) {
			addCriterion("DES_IP_MODIFICA not like", value, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaIn(List<String> values) {
			addCriterion("DES_IP_MODIFICA in", values, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaNotIn(List<String> values) {
			addCriterion("DES_IP_MODIFICA not in", values, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaBetween(String value1, String value2) {
			addCriterion("DES_IP_MODIFICA between", value1, value2, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaNotBetween(String value1, String value2) {
			addCriterion("DES_IP_MODIFICA not between", value1, value2, "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaIsNull() {
			addCriterion("ID_TIPO_VIA is null");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaIsNotNull() {
			addCriterion("ID_TIPO_VIA is not null");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaEqualTo(Integer value) {
			addCriterion("ID_TIPO_VIA =", value, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaNotEqualTo(Integer value) {
			addCriterion("ID_TIPO_VIA <>", value, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaGreaterThan(Integer value) {
			addCriterion("ID_TIPO_VIA >", value, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_TIPO_VIA >=", value, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaLessThan(Integer value) {
			addCriterion("ID_TIPO_VIA <", value, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaLessThanOrEqualTo(Integer value) {
			addCriterion("ID_TIPO_VIA <=", value, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaIn(List<Integer> values) {
			addCriterion("ID_TIPO_VIA in", values, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaNotIn(List<Integer> values) {
			addCriterion("ID_TIPO_VIA not in", values, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaBetween(Integer value1, Integer value2) {
			addCriterion("ID_TIPO_VIA between", value1, value2, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_TIPO_VIA not between", value1, value2, "idTipoVia");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoIsNull() {
			addCriterion("CUADRA_EVENTO is null");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoIsNotNull() {
			addCriterion("CUADRA_EVENTO is not null");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoEqualTo(Integer value) {
			addCriterion("CUADRA_EVENTO =", value, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoNotEqualTo(Integer value) {
			addCriterion("CUADRA_EVENTO <>", value, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoGreaterThan(Integer value) {
			addCriterion("CUADRA_EVENTO >", value, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoGreaterThanOrEqualTo(Integer value) {
			addCriterion("CUADRA_EVENTO >=", value, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoLessThan(Integer value) {
			addCriterion("CUADRA_EVENTO <", value, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoLessThanOrEqualTo(Integer value) {
			addCriterion("CUADRA_EVENTO <=", value, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoIn(List<Integer> values) {
			addCriterion("CUADRA_EVENTO in", values, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoNotIn(List<Integer> values) {
			addCriterion("CUADRA_EVENTO not in", values, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoBetween(Integer value1, Integer value2) {
			addCriterion("CUADRA_EVENTO between", value1, value2, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andCuadraEventoNotBetween(Integer value1, Integer value2) {
			addCriterion("CUADRA_EVENTO not between", value1, value2, "cuadraEvento");
			return (Criteria) this;
		}

		public Criteria andIdViaIsNull() {
			addCriterion("ID_VIA is null");
			return (Criteria) this;
		}

		public Criteria andIdViaIsNotNull() {
			addCriterion("ID_VIA is not null");
			return (Criteria) this;
		}

		public Criteria andIdViaEqualTo(Integer value) {
			addCriterion("ID_VIA =", value, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdViaNotEqualTo(Integer value) {
			addCriterion("ID_VIA <>", value, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdViaGreaterThan(Integer value) {
			addCriterion("ID_VIA >", value, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdViaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_VIA >=", value, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdViaLessThan(Integer value) {
			addCriterion("ID_VIA <", value, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdViaLessThanOrEqualTo(Integer value) {
			addCriterion("ID_VIA <=", value, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdViaIn(List<Integer> values) {
			addCriterion("ID_VIA in", values, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdViaNotIn(List<Integer> values) {
			addCriterion("ID_VIA not in", values, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdViaBetween(Integer value1, Integer value2) {
			addCriterion("ID_VIA between", value1, value2, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdViaNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_VIA not between", value1, value2, "idVia");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaIsNull() {
			addCriterion("ID_CASO_VOXIVA is null");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaIsNotNull() {
			addCriterion("ID_CASO_VOXIVA is not null");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaEqualTo(Integer value) {
			addCriterion("ID_CASO_VOXIVA =", value, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaNotEqualTo(Integer value) {
			addCriterion("ID_CASO_VOXIVA <>", value, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaGreaterThan(Integer value) {
			addCriterion("ID_CASO_VOXIVA >", value, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_CASO_VOXIVA >=", value, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaLessThan(Integer value) {
			addCriterion("ID_CASO_VOXIVA <", value, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaLessThanOrEqualTo(Integer value) {
			addCriterion("ID_CASO_VOXIVA <=", value, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaIn(List<Integer> values) {
			addCriterion("ID_CASO_VOXIVA in", values, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaNotIn(List<Integer> values) {
			addCriterion("ID_CASO_VOXIVA not in", values, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaBetween(Integer value1, Integer value2) {
			addCriterion("ID_CASO_VOXIVA between", value1, value2, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andIdCasoVoxivaNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_CASO_VOXIVA not between", value1, value2, "idCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaIsNull() {
			addCriterion("TIPO_CASO_VOXIVA is null");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaIsNotNull() {
			addCriterion("TIPO_CASO_VOXIVA is not null");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaEqualTo(Integer value) {
			addCriterion("TIPO_CASO_VOXIVA =", value, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaNotEqualTo(Integer value) {
			addCriterion("TIPO_CASO_VOXIVA <>", value, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaGreaterThan(Integer value) {
			addCriterion("TIPO_CASO_VOXIVA >", value, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaGreaterThanOrEqualTo(Integer value) {
			addCriterion("TIPO_CASO_VOXIVA >=", value, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaLessThan(Integer value) {
			addCriterion("TIPO_CASO_VOXIVA <", value, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaLessThanOrEqualTo(Integer value) {
			addCriterion("TIPO_CASO_VOXIVA <=", value, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaIn(List<Integer> values) {
			addCriterion("TIPO_CASO_VOXIVA in", values, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaNotIn(List<Integer> values) {
			addCriterion("TIPO_CASO_VOXIVA not in", values, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaBetween(Integer value1, Integer value2) {
			addCriterion("TIPO_CASO_VOXIVA between", value1, value2, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoCasoVoxivaNotBetween(Integer value1, Integer value2) {
			addCriterion("TIPO_CASO_VOXIVA not between", value1, value2, "tipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaIsNull() {
			addCriterion("SUB_TIPO_CASO_VOXIVA is null");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaIsNotNull() {
			addCriterion("SUB_TIPO_CASO_VOXIVA is not null");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaEqualTo(Integer value) {
			addCriterion("SUB_TIPO_CASO_VOXIVA =", value, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaNotEqualTo(Integer value) {
			addCriterion("SUB_TIPO_CASO_VOXIVA <>", value, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaGreaterThan(Integer value) {
			addCriterion("SUB_TIPO_CASO_VOXIVA >", value, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaGreaterThanOrEqualTo(Integer value) {
			addCriterion("SUB_TIPO_CASO_VOXIVA >=", value, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaLessThan(Integer value) {
			addCriterion("SUB_TIPO_CASO_VOXIVA <", value, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaLessThanOrEqualTo(Integer value) {
			addCriterion("SUB_TIPO_CASO_VOXIVA <=", value, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaIn(List<Integer> values) {
			addCriterion("SUB_TIPO_CASO_VOXIVA in", values, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaNotIn(List<Integer> values) {
			addCriterion("SUB_TIPO_CASO_VOXIVA not in", values, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaBetween(Integer value1, Integer value2) {
			addCriterion("SUB_TIPO_CASO_VOXIVA between", value1, value2, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andSubTipoCasoVoxivaNotBetween(Integer value1, Integer value2) {
			addCriterion("SUB_TIPO_CASO_VOXIVA not between", value1, value2, "subTipoCasoVoxiva");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaIsNull() {
			addCriterion("TIPO_INCIDENCIA is null");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaIsNotNull() {
			addCriterion("TIPO_INCIDENCIA is not null");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaEqualTo(Integer value) {
			addCriterion("TIPO_INCIDENCIA =", value, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaNotEqualTo(Integer value) {
			addCriterion("TIPO_INCIDENCIA <>", value, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaGreaterThan(Integer value) {
			addCriterion("TIPO_INCIDENCIA >", value, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaGreaterThanOrEqualTo(Integer value) {
			addCriterion("TIPO_INCIDENCIA >=", value, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaLessThan(Integer value) {
			addCriterion("TIPO_INCIDENCIA <", value, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaLessThanOrEqualTo(Integer value) {
			addCriterion("TIPO_INCIDENCIA <=", value, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaIn(List<Integer> values) {
			addCriterion("TIPO_INCIDENCIA in", values, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaNotIn(List<Integer> values) {
			addCriterion("TIPO_INCIDENCIA not in", values, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaBetween(Integer value1, Integer value2) {
			addCriterion("TIPO_INCIDENCIA between", value1, value2, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andTipoIncidenciaNotBetween(Integer value1, Integer value2) {
			addCriterion("TIPO_INCIDENCIA not between", value1, value2, "tipoIncidencia");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroIsNull() {
			addCriterion("ID_VIA_CATASTRO is null");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroIsNotNull() {
			addCriterion("ID_VIA_CATASTRO is not null");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroEqualTo(Integer value) {
			addCriterion("ID_VIA_CATASTRO =", value, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroNotEqualTo(Integer value) {
			addCriterion("ID_VIA_CATASTRO <>", value, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroGreaterThan(Integer value) {
			addCriterion("ID_VIA_CATASTRO >", value, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_VIA_CATASTRO >=", value, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroLessThan(Integer value) {
			addCriterion("ID_VIA_CATASTRO <", value, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroLessThanOrEqualTo(Integer value) {
			addCriterion("ID_VIA_CATASTRO <=", value, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroIn(List<Integer> values) {
			addCriterion("ID_VIA_CATASTRO in", values, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroNotIn(List<Integer> values) {
			addCriterion("ID_VIA_CATASTRO not in", values, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroBetween(Integer value1, Integer value2) {
			addCriterion("ID_VIA_CATASTRO between", value1, value2, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdViaCatastroNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_VIA_CATASTRO not between", value1, value2, "idViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroIsNull() {
			addCriterion("ID_TIPO_VIA_CATASTRO is null");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroIsNotNull() {
			addCriterion("ID_TIPO_VIA_CATASTRO is not null");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroEqualTo(Integer value) {
			addCriterion("ID_TIPO_VIA_CATASTRO =", value, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroNotEqualTo(Integer value) {
			addCriterion("ID_TIPO_VIA_CATASTRO <>", value, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroGreaterThan(Integer value) {
			addCriterion("ID_TIPO_VIA_CATASTRO >", value, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_TIPO_VIA_CATASTRO >=", value, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroLessThan(Integer value) {
			addCriterion("ID_TIPO_VIA_CATASTRO <", value, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroLessThanOrEqualTo(Integer value) {
			addCriterion("ID_TIPO_VIA_CATASTRO <=", value, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroIn(List<Integer> values) {
			addCriterion("ID_TIPO_VIA_CATASTRO in", values, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroNotIn(List<Integer> values) {
			addCriterion("ID_TIPO_VIA_CATASTRO not in", values, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroBetween(Integer value1, Integer value2) {
			addCriterion("ID_TIPO_VIA_CATASTRO between", value1, value2, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andIdTipoViaCatastroNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_TIPO_VIA_CATASTRO not between", value1, value2, "idTipoViaCatastro");
			return (Criteria) this;
		}

		public Criteria andEstadoIsNull() {
			addCriterion("ESTADO is null");
			return (Criteria) this;
		}

		public Criteria andEstadoIsNotNull() {
			addCriterion("ESTADO is not null");
			return (Criteria) this;
		}

		public Criteria andEstadoEqualTo(String value) {
			addCriterion("ESTADO =", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotEqualTo(String value) {
			addCriterion("ESTADO <>", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoGreaterThan(String value) {
			addCriterion("ESTADO >", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoGreaterThanOrEqualTo(String value) {
			addCriterion("ESTADO >=", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoLessThan(String value) {
			addCriterion("ESTADO <", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoLessThanOrEqualTo(String value) {
			addCriterion("ESTADO <=", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoLike(String value) {
			addCriterion("ESTADO like", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotLike(String value) {
			addCriterion("ESTADO not like", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoIn(List<String> values) {
			addCriterion("ESTADO in", values, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotIn(List<String> values) {
			addCriterion("ESTADO not in", values, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoBetween(String value1, String value2) {
			addCriterion("ESTADO between", value1, value2, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotBetween(String value1, String value2) {
			addCriterion("ESTADO not between", value1, value2, "estado");
			return (Criteria) this;
		}

		public Criteria andTipoCierreIsNull() {
			addCriterion("TIPO_CIERRE is null");
			return (Criteria) this;
		}

		public Criteria andTipoCierreIsNotNull() {
			addCriterion("TIPO_CIERRE is not null");
			return (Criteria) this;
		}

		public Criteria andTipoCierreEqualTo(String value) {
			addCriterion("TIPO_CIERRE =", value, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreNotEqualTo(String value) {
			addCriterion("TIPO_CIERRE <>", value, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreGreaterThan(String value) {
			addCriterion("TIPO_CIERRE >", value, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreGreaterThanOrEqualTo(String value) {
			addCriterion("TIPO_CIERRE >=", value, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreLessThan(String value) {
			addCriterion("TIPO_CIERRE <", value, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreLessThanOrEqualTo(String value) {
			addCriterion("TIPO_CIERRE <=", value, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreLike(String value) {
			addCriterion("TIPO_CIERRE like", value, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreNotLike(String value) {
			addCriterion("TIPO_CIERRE not like", value, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreIn(List<String> values) {
			addCriterion("TIPO_CIERRE in", values, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreNotIn(List<String> values) {
			addCriterion("TIPO_CIERRE not in", values, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreBetween(String value1, String value2) {
			addCriterion("TIPO_CIERRE between", value1, value2, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andTipoCierreNotBetween(String value1, String value2) {
			addCriterion("TIPO_CIERRE not between", value1, value2, "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andDesCalllesIsNull() {
			addCriterion("DES_CALLLES is null");
			return (Criteria) this;
		}

		public Criteria andDesCalllesIsNotNull() {
			addCriterion("DES_CALLLES is not null");
			return (Criteria) this;
		}

		public Criteria andDesCalllesEqualTo(String value) {
			addCriterion("DES_CALLLES =", value, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesNotEqualTo(String value) {
			addCriterion("DES_CALLLES <>", value, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesGreaterThan(String value) {
			addCriterion("DES_CALLLES >", value, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesGreaterThanOrEqualTo(String value) {
			addCriterion("DES_CALLLES >=", value, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesLessThan(String value) {
			addCriterion("DES_CALLLES <", value, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesLessThanOrEqualTo(String value) {
			addCriterion("DES_CALLLES <=", value, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesLike(String value) {
			addCriterion("DES_CALLLES like", value, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesNotLike(String value) {
			addCriterion("DES_CALLLES not like", value, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesIn(List<String> values) {
			addCriterion("DES_CALLLES in", values, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesNotIn(List<String> values) {
			addCriterion("DES_CALLLES not in", values, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesBetween(String value1, String value2) {
			addCriterion("DES_CALLLES between", value1, value2, "desCallles");
			return (Criteria) this;
		}

		public Criteria andDesCalllesNotBetween(String value1, String value2) {
			addCriterion("DES_CALLLES not between", value1, value2, "desCallles");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroIsNull() {
			addCriterion("USUARIO_REGISTRO is null");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroIsNotNull() {
			addCriterion("USUARIO_REGISTRO is not null");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroEqualTo(Integer value) {
			addCriterion("USUARIO_REGISTRO =", value, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroNotEqualTo(Integer value) {
			addCriterion("USUARIO_REGISTRO <>", value, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroGreaterThan(Integer value) {
			addCriterion("USUARIO_REGISTRO >", value, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroGreaterThanOrEqualTo(Integer value) {
			addCriterion("USUARIO_REGISTRO >=", value, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroLessThan(Integer value) {
			addCriterion("USUARIO_REGISTRO <", value, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroLessThanOrEqualTo(Integer value) {
			addCriterion("USUARIO_REGISTRO <=", value, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroIn(List<Integer> values) {
			addCriterion("USUARIO_REGISTRO in", values, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroNotIn(List<Integer> values) {
			addCriterion("USUARIO_REGISTRO not in", values, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroBetween(Integer value1, Integer value2) {
			addCriterion("USUARIO_REGISTRO between", value1, value2, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioRegistroNotBetween(Integer value1, Integer value2) {
			addCriterion("USUARIO_REGISTRO not between", value1, value2, "usuarioRegistro");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaIsNull() {
			addCriterion("USUARIO_MODIFICA is null");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaIsNotNull() {
			addCriterion("USUARIO_MODIFICA is not null");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaEqualTo(Integer value) {
			addCriterion("USUARIO_MODIFICA =", value, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaNotEqualTo(Integer value) {
			addCriterion("USUARIO_MODIFICA <>", value, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaGreaterThan(Integer value) {
			addCriterion("USUARIO_MODIFICA >", value, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaGreaterThanOrEqualTo(Integer value) {
			addCriterion("USUARIO_MODIFICA >=", value, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaLessThan(Integer value) {
			addCriterion("USUARIO_MODIFICA <", value, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaLessThanOrEqualTo(Integer value) {
			addCriterion("USUARIO_MODIFICA <=", value, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaIn(List<Integer> values) {
			addCriterion("USUARIO_MODIFICA in", values, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaNotIn(List<Integer> values) {
			addCriterion("USUARIO_MODIFICA not in", values, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaBetween(Integer value1, Integer value2) {
			addCriterion("USUARIO_MODIFICA between", value1, value2, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andUsuarioModificaNotBetween(Integer value1, Integer value2) {
			addCriterion("USUARIO_MODIFICA not between", value1, value2, "usuarioModifica");
			return (Criteria) this;
		}

		public Criteria andVisibleIsNull() {
			addCriterion("VISIBLE is null");
			return (Criteria) this;
		}

		public Criteria andVisibleIsNotNull() {
			addCriterion("VISIBLE is not null");
			return (Criteria) this;
		}

		public Criteria andVisibleEqualTo(String value) {
			addCriterion("VISIBLE =", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleNotEqualTo(String value) {
			addCriterion("VISIBLE <>", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleGreaterThan(String value) {
			addCriterion("VISIBLE >", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleGreaterThanOrEqualTo(String value) {
			addCriterion("VISIBLE >=", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleLessThan(String value) {
			addCriterion("VISIBLE <", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleLessThanOrEqualTo(String value) {
			addCriterion("VISIBLE <=", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleLike(String value) {
			addCriterion("VISIBLE like", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleNotLike(String value) {
			addCriterion("VISIBLE not like", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleIn(List<String> values) {
			addCriterion("VISIBLE in", values, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleNotIn(List<String> values) {
			addCriterion("VISIBLE not in", values, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleBetween(String value1, String value2) {
			addCriterion("VISIBLE between", value1, value2, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleNotBetween(String value1, String value2) {
			addCriterion("VISIBLE not between", value1, value2, "visible");
			return (Criteria) this;
		}

		public Criteria andDescripcionLikeInsensitive(String value) {
			addCriterion("upper(DESCRIPCION) like", value.toUpperCase(), "descripcion");
			return (Criteria) this;
		}

		public Criteria andSeveridadLikeInsensitive(String value) {
			addCriterion("upper(SEVERIDAD) like", value.toUpperCase(), "severidad");
			return (Criteria) this;
		}

		public Criteria andCalleLikeInsensitive(String value) {
			addCriterion("upper(CALLE) like", value.toUpperCase(), "calle");
			return (Criteria) this;
		}

		public Criteria andDireccionFinalLikeInsensitive(String value) {
			addCriterion("upper(DIRECCION_FINAL) like", value.toUpperCase(), "direccionFinal");
			return (Criteria) this;
		}

		public Criteria andNombreCalleInicioLikeInsensitive(String value) {
			addCriterion("upper(NOMBRE_CALLE_INICIO) like", value.toUpperCase(), "nombreCalleInicio");
			return (Criteria) this;
		}

		public Criteria andNombreCalleFinLikeInsensitive(String value) {
			addCriterion("upper(NOMBRE_CALLE_FIN) like", value.toUpperCase(), "nombreCalleFin");
			return (Criteria) this;
		}

		public Criteria andDesUsuRegistraLikeInsensitive(String value) {
			addCriterion("upper(DES_USU_REGISTRA) like", value.toUpperCase(), "desUsuRegistra");
			return (Criteria) this;
		}

		public Criteria andDesUsuModificaLikeInsensitive(String value) {
			addCriterion("upper(DES_USU_MODIFICA) like", value.toUpperCase(), "desUsuModifica");
			return (Criteria) this;
		}

		public Criteria andDesIpRegistraLikeInsensitive(String value) {
			addCriterion("upper(DES_IP_REGISTRA) like", value.toUpperCase(), "desIpRegistra");
			return (Criteria) this;
		}

		public Criteria andDesIpModificaLikeInsensitive(String value) {
			addCriterion("upper(DES_IP_MODIFICA) like", value.toUpperCase(), "desIpModifica");
			return (Criteria) this;
		}

		public Criteria andEstadoLikeInsensitive(String value) {
			addCriterion("upper(ESTADO) like", value.toUpperCase(), "estado");
			return (Criteria) this;
		}

		public Criteria andTipoCierreLikeInsensitive(String value) {
			addCriterion("upper(TIPO_CIERRE) like", value.toUpperCase(), "tipoCierre");
			return (Criteria) this;
		}

		public Criteria andDesCalllesLikeInsensitive(String value) {
			addCriterion("upper(DES_CALLLES) like", value.toUpperCase(), "desCallles");
			return (Criteria) this;
		}

		public Criteria andVisibleLikeInsensitive(String value) {
			addCriterion("upper(VISIBLE) like", value.toUpperCase(), "visible");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Feb 02 09:15:17 COT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GEO_INCIDENCIA_MAP
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 23 15:41:13 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}