package pe.gob.miraflores.mobile.dao.seguridad;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.seguridad.UsuarioLogin;
import pe.gob.miraflores.mobile.domain.seguridad.UsuarioLoginCriteria;

public interface UsuarioLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    int countByExample(UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    int deleteByExample(UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    int deleteByPrimaryKey(Integer ideUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    int insert(UsuarioLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    int insertSelective(UsuarioLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    List<UsuarioLogin> selectByExample(UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    UsuarioLogin selectByPrimaryKey(Integer ideUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    int updateByExampleSelective(@Param("record") UsuarioLogin record, @Param("example") UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    int updateByExample(@Param("record") UsuarioLogin record, @Param("example") UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    int updateByPrimaryKeySelective(UsuarioLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    int updateByPrimaryKey(UsuarioLogin record);
}