package pe.gob.miraflores.mobile.dao.detalleincidencia;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.detalleincidencia.GeoDetalleIncidencia;
import pe.gob.miraflores.mobile.domain.detalleincidencia.GeoDetalleIncidenciaCriteria;

public interface GeoDetalleIncidenciaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    int countByExample(GeoDetalleIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    int deleteByExample(GeoDetalleIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    int insert(GeoDetalleIncidencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    int insertSelective(GeoDetalleIncidencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    List<GeoDetalleIncidencia> selectByExample(GeoDetalleIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    int updateByExampleSelective(@Param("record") GeoDetalleIncidencia record, @Param("example") GeoDetalleIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    int updateByExample(@Param("record") GeoDetalleIncidencia record, @Param("example") GeoDetalleIncidenciaCriteria example);
}