package pe.gob.miraflores.mobile.dao.catalogo;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.catalogo.Catalogo;
import pe.gob.miraflores.mobile.domain.catalogo.CatalogoCriteria;

public interface CatalogoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    int countByExample(CatalogoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    int deleteByExample(CatalogoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    int deleteByPrimaryKey(Integer ideElemento);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    int insert(Catalogo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    int insertSelective(Catalogo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    List<Catalogo> selectByExample(CatalogoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    Catalogo selectByPrimaryKey(Integer ideElemento);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    int updateByExampleSelective(@Param("record") Catalogo record, @Param("example") CatalogoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    int updateByExample(@Param("record") Catalogo record, @Param("example") CatalogoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    int updateByPrimaryKeySelective(Catalogo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    int updateByPrimaryKey(Catalogo record);
}