package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.GeometriaLinea;
import pe.gob.miraflores.mobile.domain.mapaincidencias.GeometriaLineaCriteria;

public interface GeometriaLineaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    int countByExample(GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    int deleteByExample(GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    int deleteByPrimaryKey(Integer idLinea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    int insert(GeometriaLinea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    int insertSelective(GeometriaLinea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    List<GeometriaLinea> selectByExample(GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    GeometriaLinea selectByPrimaryKey(Integer idLinea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    int updateByExampleSelective(@Param("record") GeometriaLinea record, @Param("example") GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    int updateByExample(@Param("record") GeometriaLinea record, @Param("example") GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    int updateByPrimaryKeySelective(GeometriaLinea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_LINEA
     *
     * @mbggenerated Thu Jan 14 16:21:52 COT 2016
     */
    int updateByPrimaryKey(GeometriaLinea record);
}