package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciasRegistro;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciasRegistroCriteria;

public interface MapaIncidenciasRegistroMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	int countByExample(MapaIncidenciasRegistroCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	int deleteByExample(MapaIncidenciasRegistroCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	int deleteByPrimaryKey(Integer idIncidencia);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	int insert(MapaIncidenciasRegistro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	int insertSelective(MapaIncidenciasRegistro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	List<MapaIncidenciasRegistro> selectByExample(MapaIncidenciasRegistroCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	MapaIncidenciasRegistro selectByPrimaryKey(Integer idIncidencia);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	int updateByExampleSelective(@Param("record") MapaIncidenciasRegistro record,
			@Param("example") MapaIncidenciasRegistroCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	int updateByExample(@Param("record") MapaIncidenciasRegistro record,
			@Param("example") MapaIncidenciasRegistroCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	int updateByPrimaryKeySelective(MapaIncidenciasRegistro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Tue Jan 05 16:51:43 COT 2016
	 */
	int updateByPrimaryKey(MapaIncidenciasRegistro record);

	public List<MapaIncidenciasRegistro> listarIncidenciasConPaginacion(Map<String, Object> params);
	
	int countListarIncidenciasConPaginacion(Map<String, Object> params);
	
	public List<MapaIncidenciasRegistro> cierreCallesPorVencer(Map<String, Object> params);
	
	public List<MapaIncidenciasRegistro> cierreCallesPorIniciar(Map<String, Object> params);
	
}