package pe.gob.miraflores.mobile.dao.parametrosistema;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.parametrosistema.ParametroSistema;
import pe.gob.miraflores.mobile.domain.parametrosistema.ParametroSistemaCriteria;

public interface ParametroSistemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    int countByExample(ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    int deleteByExample(ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    int deleteByPrimaryKey(String idparametrosistema);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    int insert(ParametroSistema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    int insertSelective(ParametroSistema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    List<ParametroSistema> selectByExample(ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    ParametroSistema selectByPrimaryKey(String idparametrosistema);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    int updateByExampleSelective(@Param("record") ParametroSistema record, @Param("example") ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    int updateByExample(@Param("record") ParametroSistema record, @Param("example") ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    int updateByPrimaryKeySelective(ParametroSistema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETRO_SISTEMA
     *
     * @mbggenerated Thu Nov 26 11:59:53 COT 2015
     */
    int updateByPrimaryKey(ParametroSistema record);
}