package pe.gob.miraflores.mobile.domain.detalleincidencia;

import java.util.ArrayList;
import java.util.List;

public class GeoDetalleIncidenciaCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public GeoDetalleIncidenciaCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdInfoIsNull() {
            addCriterion("ID_INFO is null");
            return (Criteria) this;
        }

        public Criteria andIdInfoIsNotNull() {
            addCriterion("ID_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andIdInfoEqualTo(Integer value) {
            addCriterion("ID_INFO =", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoNotEqualTo(Integer value) {
            addCriterion("ID_INFO <>", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoGreaterThan(Integer value) {
            addCriterion("ID_INFO >", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_INFO >=", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoLessThan(Integer value) {
            addCriterion("ID_INFO <", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoLessThanOrEqualTo(Integer value) {
            addCriterion("ID_INFO <=", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoIn(List<Integer> values) {
            addCriterion("ID_INFO in", values, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoNotIn(List<Integer> values) {
            addCriterion("ID_INFO not in", values, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoBetween(Integer value1, Integer value2) {
            addCriterion("ID_INFO between", value1, value2, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_INFO not between", value1, value2, "idInfo");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionIsNull() {
            addCriterion("NRO_ASIGNACION is null");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionIsNotNull() {
            addCriterion("NRO_ASIGNACION is not null");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionEqualTo(Integer value) {
            addCriterion("NRO_ASIGNACION =", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionNotEqualTo(Integer value) {
            addCriterion("NRO_ASIGNACION <>", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionGreaterThan(Integer value) {
            addCriterion("NRO_ASIGNACION >", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionGreaterThanOrEqualTo(Integer value) {
            addCriterion("NRO_ASIGNACION >=", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionLessThan(Integer value) {
            addCriterion("NRO_ASIGNACION <", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionLessThanOrEqualTo(Integer value) {
            addCriterion("NRO_ASIGNACION <=", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionIn(List<Integer> values) {
            addCriterion("NRO_ASIGNACION in", values, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionNotIn(List<Integer> values) {
            addCriterion("NRO_ASIGNACION not in", values, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionBetween(Integer value1, Integer value2) {
            addCriterion("NRO_ASIGNACION between", value1, value2, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionNotBetween(Integer value1, Integer value2) {
            addCriterion("NRO_ASIGNACION not between", value1, value2, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("AREA is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("AREA is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("AREA =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("AREA <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("AREA >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("AREA >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("AREA <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("AREA <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("AREA like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("AREA not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("AREA in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("AREA not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("AREA between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("AREA not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andNroInternoIsNull() {
            addCriterion("NRO_INTERNO is null");
            return (Criteria) this;
        }

        public Criteria andNroInternoIsNotNull() {
            addCriterion("NRO_INTERNO is not null");
            return (Criteria) this;
        }

        public Criteria andNroInternoEqualTo(String value) {
            addCriterion("NRO_INTERNO =", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoNotEqualTo(String value) {
            addCriterion("NRO_INTERNO <>", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoGreaterThan(String value) {
            addCriterion("NRO_INTERNO >", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoGreaterThanOrEqualTo(String value) {
            addCriterion("NRO_INTERNO >=", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoLessThan(String value) {
            addCriterion("NRO_INTERNO <", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoLessThanOrEqualTo(String value) {
            addCriterion("NRO_INTERNO <=", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoLike(String value) {
            addCriterion("NRO_INTERNO like", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoNotLike(String value) {
            addCriterion("NRO_INTERNO not like", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoIn(List<String> values) {
            addCriterion("NRO_INTERNO in", values, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoNotIn(List<String> values) {
            addCriterion("NRO_INTERNO not in", values, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoBetween(String value1, String value2) {
            addCriterion("NRO_INTERNO between", value1, value2, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoNotBetween(String value1, String value2) {
            addCriterion("NRO_INTERNO not between", value1, value2, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andIssiIsNull() {
            addCriterion("ISSI is null");
            return (Criteria) this;
        }

        public Criteria andIssiIsNotNull() {
            addCriterion("ISSI is not null");
            return (Criteria) this;
        }

        public Criteria andIssiEqualTo(Integer value) {
            addCriterion("ISSI =", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiNotEqualTo(Integer value) {
            addCriterion("ISSI <>", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiGreaterThan(Integer value) {
            addCriterion("ISSI >", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiGreaterThanOrEqualTo(Integer value) {
            addCriterion("ISSI >=", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiLessThan(Integer value) {
            addCriterion("ISSI <", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiLessThanOrEqualTo(Integer value) {
            addCriterion("ISSI <=", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiIn(List<Integer> values) {
            addCriterion("ISSI in", values, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiNotIn(List<Integer> values) {
            addCriterion("ISSI not in", values, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiBetween(Integer value1, Integer value2) {
            addCriterion("ISSI between", value1, value2, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiNotBetween(Integer value1, Integer value2) {
            addCriterion("ISSI not between", value1, value2, "issi");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoIsNull() {
            addCriterion("TIPO_VEHICULO is null");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoIsNotNull() {
            addCriterion("TIPO_VEHICULO is not null");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoEqualTo(String value) {
            addCriterion("TIPO_VEHICULO =", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoNotEqualTo(String value) {
            addCriterion("TIPO_VEHICULO <>", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoGreaterThan(String value) {
            addCriterion("TIPO_VEHICULO >", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoGreaterThanOrEqualTo(String value) {
            addCriterion("TIPO_VEHICULO >=", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoLessThan(String value) {
            addCriterion("TIPO_VEHICULO <", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoLessThanOrEqualTo(String value) {
            addCriterion("TIPO_VEHICULO <=", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoLike(String value) {
            addCriterion("TIPO_VEHICULO like", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoNotLike(String value) {
            addCriterion("TIPO_VEHICULO not like", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoIn(List<String> values) {
            addCriterion("TIPO_VEHICULO in", values, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoNotIn(List<String> values) {
            addCriterion("TIPO_VEHICULO not in", values, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoBetween(String value1, String value2) {
            addCriterion("TIPO_VEHICULO between", value1, value2, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoNotBetween(String value1, String value2) {
            addCriterion("TIPO_VEHICULO not between", value1, value2, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoIsNull() {
            addCriterion("MARCA_VEHICULO is null");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoIsNotNull() {
            addCriterion("MARCA_VEHICULO is not null");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoEqualTo(String value) {
            addCriterion("MARCA_VEHICULO =", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoNotEqualTo(String value) {
            addCriterion("MARCA_VEHICULO <>", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoGreaterThan(String value) {
            addCriterion("MARCA_VEHICULO >", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoGreaterThanOrEqualTo(String value) {
            addCriterion("MARCA_VEHICULO >=", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoLessThan(String value) {
            addCriterion("MARCA_VEHICULO <", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoLessThanOrEqualTo(String value) {
            addCriterion("MARCA_VEHICULO <=", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoLike(String value) {
            addCriterion("MARCA_VEHICULO like", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoNotLike(String value) {
            addCriterion("MARCA_VEHICULO not like", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoIn(List<String> values) {
            addCriterion("MARCA_VEHICULO in", values, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoNotIn(List<String> values) {
            addCriterion("MARCA_VEHICULO not in", values, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoBetween(String value1, String value2) {
            addCriterion("MARCA_VEHICULO between", value1, value2, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoNotBetween(String value1, String value2) {
            addCriterion("MARCA_VEHICULO not between", value1, value2, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoIsNull() {
            addCriterion("MODELO_VEHICULO is null");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoIsNotNull() {
            addCriterion("MODELO_VEHICULO is not null");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoEqualTo(String value) {
            addCriterion("MODELO_VEHICULO =", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoNotEqualTo(String value) {
            addCriterion("MODELO_VEHICULO <>", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoGreaterThan(String value) {
            addCriterion("MODELO_VEHICULO >", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoGreaterThanOrEqualTo(String value) {
            addCriterion("MODELO_VEHICULO >=", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoLessThan(String value) {
            addCriterion("MODELO_VEHICULO <", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoLessThanOrEqualTo(String value) {
            addCriterion("MODELO_VEHICULO <=", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoLike(String value) {
            addCriterion("MODELO_VEHICULO like", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoNotLike(String value) {
            addCriterion("MODELO_VEHICULO not like", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoIn(List<String> values) {
            addCriterion("MODELO_VEHICULO in", values, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoNotIn(List<String> values) {
            addCriterion("MODELO_VEHICULO not in", values, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoBetween(String value1, String value2) {
            addCriterion("MODELO_VEHICULO between", value1, value2, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoNotBetween(String value1, String value2) {
            addCriterion("MODELO_VEHICULO not between", value1, value2, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andPlacaIsNull() {
            addCriterion("PLACA is null");
            return (Criteria) this;
        }

        public Criteria andPlacaIsNotNull() {
            addCriterion("PLACA is not null");
            return (Criteria) this;
        }

        public Criteria andPlacaEqualTo(String value) {
            addCriterion("PLACA =", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaNotEqualTo(String value) {
            addCriterion("PLACA <>", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaGreaterThan(String value) {
            addCriterion("PLACA >", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaGreaterThanOrEqualTo(String value) {
            addCriterion("PLACA >=", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaLessThan(String value) {
            addCriterion("PLACA <", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaLessThanOrEqualTo(String value) {
            addCriterion("PLACA <=", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaLike(String value) {
            addCriterion("PLACA like", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaNotLike(String value) {
            addCriterion("PLACA not like", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaIn(List<String> values) {
            addCriterion("PLACA in", values, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaNotIn(List<String> values) {
            addCriterion("PLACA not in", values, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaBetween(String value1, String value2) {
            addCriterion("PLACA between", value1, value2, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaNotBetween(String value1, String value2) {
            addCriterion("PLACA not between", value1, value2, "placa");
            return (Criteria) this;
        }

        public Criteria andTipoRadioIsNull() {
            addCriterion("TIPO_RADIO is null");
            return (Criteria) this;
        }

        public Criteria andTipoRadioIsNotNull() {
            addCriterion("TIPO_RADIO is not null");
            return (Criteria) this;
        }

        public Criteria andTipoRadioEqualTo(String value) {
            addCriterion("TIPO_RADIO =", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioNotEqualTo(String value) {
            addCriterion("TIPO_RADIO <>", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioGreaterThan(String value) {
            addCriterion("TIPO_RADIO >", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioGreaterThanOrEqualTo(String value) {
            addCriterion("TIPO_RADIO >=", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioLessThan(String value) {
            addCriterion("TIPO_RADIO <", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioLessThanOrEqualTo(String value) {
            addCriterion("TIPO_RADIO <=", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioLike(String value) {
            addCriterion("TIPO_RADIO like", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioNotLike(String value) {
            addCriterion("TIPO_RADIO not like", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioIn(List<String> values) {
            addCriterion("TIPO_RADIO in", values, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioNotIn(List<String> values) {
            addCriterion("TIPO_RADIO not in", values, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioBetween(String value1, String value2) {
            addCriterion("TIPO_RADIO between", value1, value2, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioNotBetween(String value1, String value2) {
            addCriterion("TIPO_RADIO not between", value1, value2, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioIsNull() {
            addCriterion("MODELO_RADIO is null");
            return (Criteria) this;
        }

        public Criteria andModeloRadioIsNotNull() {
            addCriterion("MODELO_RADIO is not null");
            return (Criteria) this;
        }

        public Criteria andModeloRadioEqualTo(String value) {
            addCriterion("MODELO_RADIO =", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioNotEqualTo(String value) {
            addCriterion("MODELO_RADIO <>", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioGreaterThan(String value) {
            addCriterion("MODELO_RADIO >", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioGreaterThanOrEqualTo(String value) {
            addCriterion("MODELO_RADIO >=", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioLessThan(String value) {
            addCriterion("MODELO_RADIO <", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioLessThanOrEqualTo(String value) {
            addCriterion("MODELO_RADIO <=", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioLike(String value) {
            addCriterion("MODELO_RADIO like", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioNotLike(String value) {
            addCriterion("MODELO_RADIO not like", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioIn(List<String> values) {
            addCriterion("MODELO_RADIO in", values, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioNotIn(List<String> values) {
            addCriterion("MODELO_RADIO not in", values, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioBetween(String value1, String value2) {
            addCriterion("MODELO_RADIO between", value1, value2, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioNotBetween(String value1, String value2) {
            addCriterion("MODELO_RADIO not between", value1, value2, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andZonaIsNull() {
            addCriterion("ZONA is null");
            return (Criteria) this;
        }

        public Criteria andZonaIsNotNull() {
            addCriterion("ZONA is not null");
            return (Criteria) this;
        }

        public Criteria andZonaEqualTo(String value) {
            addCriterion("ZONA =", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotEqualTo(String value) {
            addCriterion("ZONA <>", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaGreaterThan(String value) {
            addCriterion("ZONA >", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaGreaterThanOrEqualTo(String value) {
            addCriterion("ZONA >=", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaLessThan(String value) {
            addCriterion("ZONA <", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaLessThanOrEqualTo(String value) {
            addCriterion("ZONA <=", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaLike(String value) {
            addCriterion("ZONA like", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotLike(String value) {
            addCriterion("ZONA not like", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaIn(List<String> values) {
            addCriterion("ZONA in", values, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotIn(List<String> values) {
            addCriterion("ZONA not in", values, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaBetween(String value1, String value2) {
            addCriterion("ZONA between", value1, value2, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotBetween(String value1, String value2) {
            addCriterion("ZONA not between", value1, value2, "zona");
            return (Criteria) this;
        }

        public Criteria andSubZonaIsNull() {
            addCriterion("SUB_ZONA is null");
            return (Criteria) this;
        }

        public Criteria andSubZonaIsNotNull() {
            addCriterion("SUB_ZONA is not null");
            return (Criteria) this;
        }

        public Criteria andSubZonaEqualTo(String value) {
            addCriterion("SUB_ZONA =", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotEqualTo(String value) {
            addCriterion("SUB_ZONA <>", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaGreaterThan(String value) {
            addCriterion("SUB_ZONA >", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_ZONA >=", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLessThan(String value) {
            addCriterion("SUB_ZONA <", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLessThanOrEqualTo(String value) {
            addCriterion("SUB_ZONA <=", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLike(String value) {
            addCriterion("SUB_ZONA like", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotLike(String value) {
            addCriterion("SUB_ZONA not like", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaIn(List<String> values) {
            addCriterion("SUB_ZONA in", values, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotIn(List<String> values) {
            addCriterion("SUB_ZONA not in", values, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaBetween(String value1, String value2) {
            addCriterion("SUB_ZONA between", value1, value2, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotBetween(String value1, String value2) {
            addCriterion("SUB_ZONA not between", value1, value2, "subZona");
            return (Criteria) this;
        }

        public Criteria andAreaLikeInsensitive(String value) {
            addCriterion("upper(AREA) like", value.toUpperCase(), "area");
            return (Criteria) this;
        }

        public Criteria andNroInternoLikeInsensitive(String value) {
            addCriterion("upper(NRO_INTERNO) like", value.toUpperCase(), "nroInterno");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoLikeInsensitive(String value) {
            addCriterion("upper(TIPO_VEHICULO) like", value.toUpperCase(), "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoLikeInsensitive(String value) {
            addCriterion("upper(MARCA_VEHICULO) like", value.toUpperCase(), "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoLikeInsensitive(String value) {
            addCriterion("upper(MODELO_VEHICULO) like", value.toUpperCase(), "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andPlacaLikeInsensitive(String value) {
            addCriterion("upper(PLACA) like", value.toUpperCase(), "placa");
            return (Criteria) this;
        }

        public Criteria andTipoRadioLikeInsensitive(String value) {
            addCriterion("upper(TIPO_RADIO) like", value.toUpperCase(), "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioLikeInsensitive(String value) {
            addCriterion("upper(MODELO_RADIO) like", value.toUpperCase(), "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andZonaLikeInsensitive(String value) {
            addCriterion("upper(ZONA) like", value.toUpperCase(), "zona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLikeInsensitive(String value) {
            addCriterion("upper(SUB_ZONA) like", value.toUpperCase(), "subZona");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 27 16:05:20 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}