package pe.gob.miraflores.mobile.domain.detalleincidencia;

public class GeoDetalleIncidencia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.ID_INFO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private Integer idInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.NRO_ASIGNACION
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private Integer nroAsignacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.AREA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.NRO_INTERNO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String nroInterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.ISSI
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private Integer issi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.TIPO_VEHICULO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String tipoVehiculo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.MARCA_VEHICULO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String marcaVehiculo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.MODELO_VEHICULO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String modeloVehiculo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.PLACA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String placa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.TIPO_RADIO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String tipoRadio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.MODELO_RADIO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String modeloRadio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.ZONA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String zona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_INFO_TETRA.SUB_ZONA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    private String subZona;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.ID_INFO
     *
     * @return the value of GEO_INFO_TETRA.ID_INFO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public Integer getIdInfo() {
        return idInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.ID_INFO
     *
     * @param idInfo the value for GEO_INFO_TETRA.ID_INFO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setIdInfo(Integer idInfo) {
        this.idInfo = idInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.NRO_ASIGNACION
     *
     * @return the value of GEO_INFO_TETRA.NRO_ASIGNACION
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public Integer getNroAsignacion() {
        return nroAsignacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.NRO_ASIGNACION
     *
     * @param nroAsignacion the value for GEO_INFO_TETRA.NRO_ASIGNACION
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setNroAsignacion(Integer nroAsignacion) {
        this.nroAsignacion = nroAsignacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.AREA
     *
     * @return the value of GEO_INFO_TETRA.AREA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.AREA
     *
     * @param area the value for GEO_INFO_TETRA.AREA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.NRO_INTERNO
     *
     * @return the value of GEO_INFO_TETRA.NRO_INTERNO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getNroInterno() {
        return nroInterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.NRO_INTERNO
     *
     * @param nroInterno the value for GEO_INFO_TETRA.NRO_INTERNO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setNroInterno(String nroInterno) {
        this.nroInterno = nroInterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.ISSI
     *
     * @return the value of GEO_INFO_TETRA.ISSI
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public Integer getIssi() {
        return issi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.ISSI
     *
     * @param issi the value for GEO_INFO_TETRA.ISSI
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setIssi(Integer issi) {
        this.issi = issi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.TIPO_VEHICULO
     *
     * @return the value of GEO_INFO_TETRA.TIPO_VEHICULO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getTipoVehiculo() {
        return tipoVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.TIPO_VEHICULO
     *
     * @param tipoVehiculo the value for GEO_INFO_TETRA.TIPO_VEHICULO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setTipoVehiculo(String tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.MARCA_VEHICULO
     *
     * @return the value of GEO_INFO_TETRA.MARCA_VEHICULO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getMarcaVehiculo() {
        return marcaVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.MARCA_VEHICULO
     *
     * @param marcaVehiculo the value for GEO_INFO_TETRA.MARCA_VEHICULO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setMarcaVehiculo(String marcaVehiculo) {
        this.marcaVehiculo = marcaVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.MODELO_VEHICULO
     *
     * @return the value of GEO_INFO_TETRA.MODELO_VEHICULO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getModeloVehiculo() {
        return modeloVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.MODELO_VEHICULO
     *
     * @param modeloVehiculo the value for GEO_INFO_TETRA.MODELO_VEHICULO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setModeloVehiculo(String modeloVehiculo) {
        this.modeloVehiculo = modeloVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.PLACA
     *
     * @return the value of GEO_INFO_TETRA.PLACA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getPlaca() {
        return placa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.PLACA
     *
     * @param placa the value for GEO_INFO_TETRA.PLACA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setPlaca(String placa) {
        this.placa = placa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.TIPO_RADIO
     *
     * @return the value of GEO_INFO_TETRA.TIPO_RADIO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getTipoRadio() {
        return tipoRadio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.TIPO_RADIO
     *
     * @param tipoRadio the value for GEO_INFO_TETRA.TIPO_RADIO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setTipoRadio(String tipoRadio) {
        this.tipoRadio = tipoRadio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.MODELO_RADIO
     *
     * @return the value of GEO_INFO_TETRA.MODELO_RADIO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getModeloRadio() {
        return modeloRadio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.MODELO_RADIO
     *
     * @param modeloRadio the value for GEO_INFO_TETRA.MODELO_RADIO
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setModeloRadio(String modeloRadio) {
        this.modeloRadio = modeloRadio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.ZONA
     *
     * @return the value of GEO_INFO_TETRA.ZONA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getZona() {
        return zona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.ZONA
     *
     * @param zona the value for GEO_INFO_TETRA.ZONA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setZona(String zona) {
        this.zona = zona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_INFO_TETRA.SUB_ZONA
     *
     * @return the value of GEO_INFO_TETRA.SUB_ZONA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public String getSubZona() {
        return subZona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_INFO_TETRA.SUB_ZONA
     *
     * @param subZona the value for GEO_INFO_TETRA.SUB_ZONA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    public void setSubZona(String subZona) {
        this.subZona = subZona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GeoDetalleIncidencia other = (GeoDetalleIncidencia) that;
        return (this.getIdInfo() == null ? other.getIdInfo() == null : this.getIdInfo().equals(other.getIdInfo()))
            && (this.getNroAsignacion() == null ? other.getNroAsignacion() == null : this.getNroAsignacion().equals(other.getNroAsignacion()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getNroInterno() == null ? other.getNroInterno() == null : this.getNroInterno().equals(other.getNroInterno()))
            && (this.getIssi() == null ? other.getIssi() == null : this.getIssi().equals(other.getIssi()))
            && (this.getTipoVehiculo() == null ? other.getTipoVehiculo() == null : this.getTipoVehiculo().equals(other.getTipoVehiculo()))
            && (this.getMarcaVehiculo() == null ? other.getMarcaVehiculo() == null : this.getMarcaVehiculo().equals(other.getMarcaVehiculo()))
            && (this.getModeloVehiculo() == null ? other.getModeloVehiculo() == null : this.getModeloVehiculo().equals(other.getModeloVehiculo()))
            && (this.getPlaca() == null ? other.getPlaca() == null : this.getPlaca().equals(other.getPlaca()))
            && (this.getTipoRadio() == null ? other.getTipoRadio() == null : this.getTipoRadio().equals(other.getTipoRadio()))
            && (this.getModeloRadio() == null ? other.getModeloRadio() == null : this.getModeloRadio().equals(other.getModeloRadio()))
            && (this.getZona() == null ? other.getZona() == null : this.getZona().equals(other.getZona()))
            && (this.getSubZona() == null ? other.getSubZona() == null : this.getSubZona().equals(other.getSubZona()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_INFO_TETRA
     *
     * @mbggenerated Fri Nov 27 16:05:20 COT 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdInfo() == null) ? 0 : getIdInfo().hashCode());
        result = prime * result + ((getNroAsignacion() == null) ? 0 : getNroAsignacion().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getNroInterno() == null) ? 0 : getNroInterno().hashCode());
        result = prime * result + ((getIssi() == null) ? 0 : getIssi().hashCode());
        result = prime * result + ((getTipoVehiculo() == null) ? 0 : getTipoVehiculo().hashCode());
        result = prime * result + ((getMarcaVehiculo() == null) ? 0 : getMarcaVehiculo().hashCode());
        result = prime * result + ((getModeloVehiculo() == null) ? 0 : getModeloVehiculo().hashCode());
        result = prime * result + ((getPlaca() == null) ? 0 : getPlaca().hashCode());
        result = prime * result + ((getTipoRadio() == null) ? 0 : getTipoRadio().hashCode());
        result = prime * result + ((getModeloRadio() == null) ? 0 : getModeloRadio().hashCode());
        result = prime * result + ((getZona() == null) ? 0 : getZona().hashCode());
        result = prime * result + ((getSubZona() == null) ? 0 : getSubZona().hashCode());
        return result;
    }
}