package pe.gob.miraflores.mobile.domain.catalogo;

import java.util.Date;

public class Catalogo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.IDE_ELEMENTO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private Integer ideElemento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.IDE_GRUPO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private Integer ideGrupo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.COD_CODIGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private String codCodigo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.DES_NOMBRE
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private String desNombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.CLV_ABREVIAR
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private String clvAbreviar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.IDE_ELEMENTO1
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private Integer ideElemento1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.IND_ESTADO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private String indEstado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.FEC_FECHA_CREACION
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private Date fecFechaCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.REFERENCIA
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private String referencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.REFERENCIA1
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private String referencia1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CTLMELECGO.REFERENCIA2
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    private String referencia2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.IDE_ELEMENTO
     *
     * @return the value of CTLMELECGO.IDE_ELEMENTO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public Integer getIdeElemento() {
        return ideElemento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.IDE_ELEMENTO
     *
     * @param ideElemento the value for CTLMELECGO.IDE_ELEMENTO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setIdeElemento(Integer ideElemento) {
        this.ideElemento = ideElemento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.IDE_GRUPO
     *
     * @return the value of CTLMELECGO.IDE_GRUPO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public Integer getIdeGrupo() {
        return ideGrupo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.IDE_GRUPO
     *
     * @param ideGrupo the value for CTLMELECGO.IDE_GRUPO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setIdeGrupo(Integer ideGrupo) {
        this.ideGrupo = ideGrupo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.COD_CODIGO
     *
     * @return the value of CTLMELECGO.COD_CODIGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public String getCodCodigo() {
        return codCodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.COD_CODIGO
     *
     * @param codCodigo the value for CTLMELECGO.COD_CODIGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setCodCodigo(String codCodigo) {
        this.codCodigo = codCodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.DES_NOMBRE
     *
     * @return the value of CTLMELECGO.DES_NOMBRE
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public String getDesNombre() {
        return desNombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.DES_NOMBRE
     *
     * @param desNombre the value for CTLMELECGO.DES_NOMBRE
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setDesNombre(String desNombre) {
        this.desNombre = desNombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.CLV_ABREVIAR
     *
     * @return the value of CTLMELECGO.CLV_ABREVIAR
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public String getClvAbreviar() {
        return clvAbreviar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.CLV_ABREVIAR
     *
     * @param clvAbreviar the value for CTLMELECGO.CLV_ABREVIAR
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setClvAbreviar(String clvAbreviar) {
        this.clvAbreviar = clvAbreviar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.IDE_ELEMENTO1
     *
     * @return the value of CTLMELECGO.IDE_ELEMENTO1
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public Integer getIdeElemento1() {
        return ideElemento1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.IDE_ELEMENTO1
     *
     * @param ideElemento1 the value for CTLMELECGO.IDE_ELEMENTO1
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setIdeElemento1(Integer ideElemento1) {
        this.ideElemento1 = ideElemento1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.IND_ESTADO
     *
     * @return the value of CTLMELECGO.IND_ESTADO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public String getIndEstado() {
        return indEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.IND_ESTADO
     *
     * @param indEstado the value for CTLMELECGO.IND_ESTADO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setIndEstado(String indEstado) {
        this.indEstado = indEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.FEC_FECHA_CREACION
     *
     * @return the value of CTLMELECGO.FEC_FECHA_CREACION
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public Date getFecFechaCreacion() {
        return fecFechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.FEC_FECHA_CREACION
     *
     * @param fecFechaCreacion the value for CTLMELECGO.FEC_FECHA_CREACION
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setFecFechaCreacion(Date fecFechaCreacion) {
        this.fecFechaCreacion = fecFechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.REFERENCIA
     *
     * @return the value of CTLMELECGO.REFERENCIA
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public String getReferencia() {
        return referencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.REFERENCIA
     *
     * @param referencia the value for CTLMELECGO.REFERENCIA
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.REFERENCIA1
     *
     * @return the value of CTLMELECGO.REFERENCIA1
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public String getReferencia1() {
        return referencia1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.REFERENCIA1
     *
     * @param referencia1 the value for CTLMELECGO.REFERENCIA1
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setReferencia1(String referencia1) {
        this.referencia1 = referencia1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTLMELECGO.REFERENCIA2
     *
     * @return the value of CTLMELECGO.REFERENCIA2
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public String getReferencia2() {
        return referencia2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTLMELECGO.REFERENCIA2
     *
     * @param referencia2 the value for CTLMELECGO.REFERENCIA2
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    public void setReferencia2(String referencia2) {
        this.referencia2 = referencia2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Catalogo other = (Catalogo) that;
        return (this.getIdeElemento() == null ? other.getIdeElemento() == null : this.getIdeElemento().equals(other.getIdeElemento()))
            && (this.getIdeGrupo() == null ? other.getIdeGrupo() == null : this.getIdeGrupo().equals(other.getIdeGrupo()))
            && (this.getCodCodigo() == null ? other.getCodCodigo() == null : this.getCodCodigo().equals(other.getCodCodigo()))
            && (this.getDesNombre() == null ? other.getDesNombre() == null : this.getDesNombre().equals(other.getDesNombre()))
            && (this.getClvAbreviar() == null ? other.getClvAbreviar() == null : this.getClvAbreviar().equals(other.getClvAbreviar()))
            && (this.getIdeElemento1() == null ? other.getIdeElemento1() == null : this.getIdeElemento1().equals(other.getIdeElemento1()))
            && (this.getIndEstado() == null ? other.getIndEstado() == null : this.getIndEstado().equals(other.getIndEstado()))
            && (this.getFecFechaCreacion() == null ? other.getFecFechaCreacion() == null : this.getFecFechaCreacion().equals(other.getFecFechaCreacion()))
            && (this.getReferencia() == null ? other.getReferencia() == null : this.getReferencia().equals(other.getReferencia()))
            && (this.getReferencia1() == null ? other.getReferencia1() == null : this.getReferencia1().equals(other.getReferencia1()))
            && (this.getReferencia2() == null ? other.getReferencia2() == null : this.getReferencia2().equals(other.getReferencia2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CTLMELECGO
     *
     * @mbggenerated Thu Nov 26 12:50:22 COT 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdeElemento() == null) ? 0 : getIdeElemento().hashCode());
        result = prime * result + ((getIdeGrupo() == null) ? 0 : getIdeGrupo().hashCode());
        result = prime * result + ((getCodCodigo() == null) ? 0 : getCodCodigo().hashCode());
        result = prime * result + ((getDesNombre() == null) ? 0 : getDesNombre().hashCode());
        result = prime * result + ((getClvAbreviar() == null) ? 0 : getClvAbreviar().hashCode());
        result = prime * result + ((getIdeElemento1() == null) ? 0 : getIdeElemento1().hashCode());
        result = prime * result + ((getIndEstado() == null) ? 0 : getIndEstado().hashCode());
        result = prime * result + ((getFecFechaCreacion() == null) ? 0 : getFecFechaCreacion().hashCode());
        result = prime * result + ((getReferencia() == null) ? 0 : getReferencia().hashCode());
        result = prime * result + ((getReferencia1() == null) ? 0 : getReferencia1().hashCode());
        result = prime * result + ((getReferencia2() == null) ? 0 : getReferencia2().hashCode());
        return result;
    }
}