package pe.gob.miraflores.mobile.domain.seguridad;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsuarioLoginCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public UsuarioLoginCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdeUsuarioIsNull() {
            addCriterion("IDE_USUARIO is null");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioIsNotNull() {
            addCriterion("IDE_USUARIO is not null");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioEqualTo(Integer value) {
            addCriterion("IDE_USUARIO =", value, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioNotEqualTo(Integer value) {
            addCriterion("IDE_USUARIO <>", value, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioGreaterThan(Integer value) {
            addCriterion("IDE_USUARIO >", value, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("IDE_USUARIO >=", value, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioLessThan(Integer value) {
            addCriterion("IDE_USUARIO <", value, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioLessThanOrEqualTo(Integer value) {
            addCriterion("IDE_USUARIO <=", value, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioIn(List<Integer> values) {
            addCriterion("IDE_USUARIO in", values, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioNotIn(List<Integer> values) {
            addCriterion("IDE_USUARIO not in", values, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioBetween(Integer value1, Integer value2) {
            addCriterion("IDE_USUARIO between", value1, value2, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeUsuarioNotBetween(Integer value1, Integer value2) {
            addCriterion("IDE_USUARIO not between", value1, value2, "ideUsuario");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoIsNull() {
            addCriterion("IDE_ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoIsNotNull() {
            addCriterion("IDE_ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoEqualTo(Integer value) {
            addCriterion("IDE_ESTADO =", value, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoNotEqualTo(Integer value) {
            addCriterion("IDE_ESTADO <>", value, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoGreaterThan(Integer value) {
            addCriterion("IDE_ESTADO >", value, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("IDE_ESTADO >=", value, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoLessThan(Integer value) {
            addCriterion("IDE_ESTADO <", value, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("IDE_ESTADO <=", value, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoIn(List<Integer> values) {
            addCriterion("IDE_ESTADO in", values, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoNotIn(List<Integer> values) {
            addCriterion("IDE_ESTADO not in", values, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoBetween(Integer value1, Integer value2) {
            addCriterion("IDE_ESTADO between", value1, value2, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andIdeEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("IDE_ESTADO not between", value1, value2, "ideEstado");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserIsNull() {
            addCriterion("DES_LOGIN_USER is null");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserIsNotNull() {
            addCriterion("DES_LOGIN_USER is not null");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserEqualTo(String value) {
            addCriterion("DES_LOGIN_USER =", value, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserNotEqualTo(String value) {
            addCriterion("DES_LOGIN_USER <>", value, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserGreaterThan(String value) {
            addCriterion("DES_LOGIN_USER >", value, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserGreaterThanOrEqualTo(String value) {
            addCriterion("DES_LOGIN_USER >=", value, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserLessThan(String value) {
            addCriterion("DES_LOGIN_USER <", value, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserLessThanOrEqualTo(String value) {
            addCriterion("DES_LOGIN_USER <=", value, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserLike(String value) {
            addCriterion("DES_LOGIN_USER like", value, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserNotLike(String value) {
            addCriterion("DES_LOGIN_USER not like", value, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserIn(List<String> values) {
            addCriterion("DES_LOGIN_USER in", values, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserNotIn(List<String> values) {
            addCriterion("DES_LOGIN_USER not in", values, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserBetween(String value1, String value2) {
            addCriterion("DES_LOGIN_USER between", value1, value2, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserNotBetween(String value1, String value2) {
            addCriterion("DES_LOGIN_USER not between", value1, value2, "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserIsNull() {
            addCriterion("CLV_CLAVE_USER is null");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserIsNotNull() {
            addCriterion("CLV_CLAVE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserEqualTo(String value) {
            addCriterion("CLV_CLAVE_USER =", value, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserNotEqualTo(String value) {
            addCriterion("CLV_CLAVE_USER <>", value, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserGreaterThan(String value) {
            addCriterion("CLV_CLAVE_USER >", value, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserGreaterThanOrEqualTo(String value) {
            addCriterion("CLV_CLAVE_USER >=", value, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserLessThan(String value) {
            addCriterion("CLV_CLAVE_USER <", value, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserLessThanOrEqualTo(String value) {
            addCriterion("CLV_CLAVE_USER <=", value, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserLike(String value) {
            addCriterion("CLV_CLAVE_USER like", value, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserNotLike(String value) {
            addCriterion("CLV_CLAVE_USER not like", value, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserIn(List<String> values) {
            addCriterion("CLV_CLAVE_USER in", values, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserNotIn(List<String> values) {
            addCriterion("CLV_CLAVE_USER not in", values, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserBetween(String value1, String value2) {
            addCriterion("CLV_CLAVE_USER between", value1, value2, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserNotBetween(String value1, String value2) {
            addCriterion("CLV_CLAVE_USER not between", value1, value2, "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andIdeRolIsNull() {
            addCriterion("IDE_ROL is null");
            return (Criteria) this;
        }

        public Criteria andIdeRolIsNotNull() {
            addCriterion("IDE_ROL is not null");
            return (Criteria) this;
        }

        public Criteria andIdeRolEqualTo(Integer value) {
            addCriterion("IDE_ROL =", value, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdeRolNotEqualTo(Integer value) {
            addCriterion("IDE_ROL <>", value, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdeRolGreaterThan(Integer value) {
            addCriterion("IDE_ROL >", value, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdeRolGreaterThanOrEqualTo(Integer value) {
            addCriterion("IDE_ROL >=", value, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdeRolLessThan(Integer value) {
            addCriterion("IDE_ROL <", value, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdeRolLessThanOrEqualTo(Integer value) {
            addCriterion("IDE_ROL <=", value, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdeRolIn(List<Integer> values) {
            addCriterion("IDE_ROL in", values, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdeRolNotIn(List<Integer> values) {
            addCriterion("IDE_ROL not in", values, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdeRolBetween(Integer value1, Integer value2) {
            addCriterion("IDE_ROL between", value1, value2, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdeRolNotBetween(Integer value1, Integer value2) {
            addCriterion("IDE_ROL not between", value1, value2, "ideRol");
            return (Criteria) this;
        }

        public Criteria andIdePersonaIsNull() {
            addCriterion("IDE_PERSONA is null");
            return (Criteria) this;
        }

        public Criteria andIdePersonaIsNotNull() {
            addCriterion("IDE_PERSONA is not null");
            return (Criteria) this;
        }

        public Criteria andIdePersonaEqualTo(Integer value) {
            addCriterion("IDE_PERSONA =", value, "idePersona");
            return (Criteria) this;
        }

        public Criteria andIdePersonaNotEqualTo(Integer value) {
            addCriterion("IDE_PERSONA <>", value, "idePersona");
            return (Criteria) this;
        }

        public Criteria andIdePersonaGreaterThan(Integer value) {
            addCriterion("IDE_PERSONA >", value, "idePersona");
            return (Criteria) this;
        }

        public Criteria andIdePersonaGreaterThanOrEqualTo(Integer value) {
            addCriterion("IDE_PERSONA >=", value, "idePersona");
            return (Criteria) this;
        }

        public Criteria andIdePersonaLessThan(Integer value) {
            addCriterion("IDE_PERSONA <", value, "idePersona");
            return (Criteria) this;
        }

        public Criteria andIdePersonaLessThanOrEqualTo(Integer value) {
            addCriterion("IDE_PERSONA <=", value, "idePersona");
            return (Criteria) this;
        }

        public Criteria andIdePersonaIn(List<Integer> values) {
            addCriterion("IDE_PERSONA in", values, "idePersona");
            return (Criteria) this;
        }

        public Criteria andIdePersonaNotIn(List<Integer> values) {
            addCriterion("IDE_PERSONA not in", values, "idePersona");
            return (Criteria) this;
        }

        public Criteria andIdePersonaBetween(Integer value1, Integer value2) {
            addCriterion("IDE_PERSONA between", value1, value2, "idePersona");
            return (Criteria) this;
        }

        public Criteria andIdePersonaNotBetween(Integer value1, Integer value2) {
            addCriterion("IDE_PERSONA not between", value1, value2, "idePersona");
            return (Criteria) this;
        }

        public Criteria andFecRegistraIsNull() {
            addCriterion("FEC_REGISTRA is null");
            return (Criteria) this;
        }

        public Criteria andFecRegistraIsNotNull() {
            addCriterion("FEC_REGISTRA is not null");
            return (Criteria) this;
        }

        public Criteria andFecRegistraEqualTo(Date value) {
            addCriterion("FEC_REGISTRA =", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraNotEqualTo(Date value) {
            addCriterion("FEC_REGISTRA <>", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraGreaterThan(Date value) {
            addCriterion("FEC_REGISTRA >", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraGreaterThanOrEqualTo(Date value) {
            addCriterion("FEC_REGISTRA >=", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraLessThan(Date value) {
            addCriterion("FEC_REGISTRA <", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraLessThanOrEqualTo(Date value) {
            addCriterion("FEC_REGISTRA <=", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraIn(List<Date> values) {
            addCriterion("FEC_REGISTRA in", values, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraNotIn(List<Date> values) {
            addCriterion("FEC_REGISTRA not in", values, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraBetween(Date value1, Date value2) {
            addCriterion("FEC_REGISTRA between", value1, value2, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraNotBetween(Date value1, Date value2) {
            addCriterion("FEC_REGISTRA not between", value1, value2, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecModificaIsNull() {
            addCriterion("FEC_MODIFICA is null");
            return (Criteria) this;
        }

        public Criteria andFecModificaIsNotNull() {
            addCriterion("FEC_MODIFICA is not null");
            return (Criteria) this;
        }

        public Criteria andFecModificaEqualTo(Date value) {
            addCriterion("FEC_MODIFICA =", value, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andFecModificaNotEqualTo(Date value) {
            addCriterion("FEC_MODIFICA <>", value, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andFecModificaGreaterThan(Date value) {
            addCriterion("FEC_MODIFICA >", value, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andFecModificaGreaterThanOrEqualTo(Date value) {
            addCriterion("FEC_MODIFICA >=", value, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andFecModificaLessThan(Date value) {
            addCriterion("FEC_MODIFICA <", value, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andFecModificaLessThanOrEqualTo(Date value) {
            addCriterion("FEC_MODIFICA <=", value, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andFecModificaIn(List<Date> values) {
            addCriterion("FEC_MODIFICA in", values, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andFecModificaNotIn(List<Date> values) {
            addCriterion("FEC_MODIFICA not in", values, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andFecModificaBetween(Date value1, Date value2) {
            addCriterion("FEC_MODIFICA between", value1, value2, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andFecModificaNotBetween(Date value1, Date value2) {
            addCriterion("FEC_MODIFICA not between", value1, value2, "fecModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraIsNull() {
            addCriterion("DES_USU_REGISTRA is null");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraIsNotNull() {
            addCriterion("DES_USU_REGISTRA is not null");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraEqualTo(String value) {
            addCriterion("DES_USU_REGISTRA =", value, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraNotEqualTo(String value) {
            addCriterion("DES_USU_REGISTRA <>", value, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraGreaterThan(String value) {
            addCriterion("DES_USU_REGISTRA >", value, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraGreaterThanOrEqualTo(String value) {
            addCriterion("DES_USU_REGISTRA >=", value, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraLessThan(String value) {
            addCriterion("DES_USU_REGISTRA <", value, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraLessThanOrEqualTo(String value) {
            addCriterion("DES_USU_REGISTRA <=", value, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraLike(String value) {
            addCriterion("DES_USU_REGISTRA like", value, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraNotLike(String value) {
            addCriterion("DES_USU_REGISTRA not like", value, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraIn(List<String> values) {
            addCriterion("DES_USU_REGISTRA in", values, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraNotIn(List<String> values) {
            addCriterion("DES_USU_REGISTRA not in", values, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraBetween(String value1, String value2) {
            addCriterion("DES_USU_REGISTRA between", value1, value2, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraNotBetween(String value1, String value2) {
            addCriterion("DES_USU_REGISTRA not between", value1, value2, "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaIsNull() {
            addCriterion("DES_USU_MODIFICA is null");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaIsNotNull() {
            addCriterion("DES_USU_MODIFICA is not null");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaEqualTo(String value) {
            addCriterion("DES_USU_MODIFICA =", value, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaNotEqualTo(String value) {
            addCriterion("DES_USU_MODIFICA <>", value, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaGreaterThan(String value) {
            addCriterion("DES_USU_MODIFICA >", value, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaGreaterThanOrEqualTo(String value) {
            addCriterion("DES_USU_MODIFICA >=", value, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaLessThan(String value) {
            addCriterion("DES_USU_MODIFICA <", value, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaLessThanOrEqualTo(String value) {
            addCriterion("DES_USU_MODIFICA <=", value, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaLike(String value) {
            addCriterion("DES_USU_MODIFICA like", value, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaNotLike(String value) {
            addCriterion("DES_USU_MODIFICA not like", value, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaIn(List<String> values) {
            addCriterion("DES_USU_MODIFICA in", values, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaNotIn(List<String> values) {
            addCriterion("DES_USU_MODIFICA not in", values, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaBetween(String value1, String value2) {
            addCriterion("DES_USU_MODIFICA between", value1, value2, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaNotBetween(String value1, String value2) {
            addCriterion("DES_USU_MODIFICA not between", value1, value2, "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraIsNull() {
            addCriterion("DES_IP_REGISTRA is null");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraIsNotNull() {
            addCriterion("DES_IP_REGISTRA is not null");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraEqualTo(String value) {
            addCriterion("DES_IP_REGISTRA =", value, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraNotEqualTo(String value) {
            addCriterion("DES_IP_REGISTRA <>", value, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraGreaterThan(String value) {
            addCriterion("DES_IP_REGISTRA >", value, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraGreaterThanOrEqualTo(String value) {
            addCriterion("DES_IP_REGISTRA >=", value, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraLessThan(String value) {
            addCriterion("DES_IP_REGISTRA <", value, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraLessThanOrEqualTo(String value) {
            addCriterion("DES_IP_REGISTRA <=", value, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraLike(String value) {
            addCriterion("DES_IP_REGISTRA like", value, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraNotLike(String value) {
            addCriterion("DES_IP_REGISTRA not like", value, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraIn(List<String> values) {
            addCriterion("DES_IP_REGISTRA in", values, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraNotIn(List<String> values) {
            addCriterion("DES_IP_REGISTRA not in", values, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraBetween(String value1, String value2) {
            addCriterion("DES_IP_REGISTRA between", value1, value2, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraNotBetween(String value1, String value2) {
            addCriterion("DES_IP_REGISTRA not between", value1, value2, "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaIsNull() {
            addCriterion("DES_IP_MODIFICA is null");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaIsNotNull() {
            addCriterion("DES_IP_MODIFICA is not null");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaEqualTo(String value) {
            addCriterion("DES_IP_MODIFICA =", value, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaNotEqualTo(String value) {
            addCriterion("DES_IP_MODIFICA <>", value, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaGreaterThan(String value) {
            addCriterion("DES_IP_MODIFICA >", value, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaGreaterThanOrEqualTo(String value) {
            addCriterion("DES_IP_MODIFICA >=", value, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaLessThan(String value) {
            addCriterion("DES_IP_MODIFICA <", value, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaLessThanOrEqualTo(String value) {
            addCriterion("DES_IP_MODIFICA <=", value, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaLike(String value) {
            addCriterion("DES_IP_MODIFICA like", value, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaNotLike(String value) {
            addCriterion("DES_IP_MODIFICA not like", value, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaIn(List<String> values) {
            addCriterion("DES_IP_MODIFICA in", values, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaNotIn(List<String> values) {
            addCriterion("DES_IP_MODIFICA not in", values, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaBetween(String value1, String value2) {
            addCriterion("DES_IP_MODIFICA between", value1, value2, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaNotBetween(String value1, String value2) {
            addCriterion("DES_IP_MODIFICA not between", value1, value2, "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaIsNull() {
            addCriterion("IN_CUENTA_EXPIRADA is null");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaIsNotNull() {
            addCriterion("IN_CUENTA_EXPIRADA is not null");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaEqualTo(String value) {
            addCriterion("IN_CUENTA_EXPIRADA =", value, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaNotEqualTo(String value) {
            addCriterion("IN_CUENTA_EXPIRADA <>", value, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaGreaterThan(String value) {
            addCriterion("IN_CUENTA_EXPIRADA >", value, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaGreaterThanOrEqualTo(String value) {
            addCriterion("IN_CUENTA_EXPIRADA >=", value, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaLessThan(String value) {
            addCriterion("IN_CUENTA_EXPIRADA <", value, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaLessThanOrEqualTo(String value) {
            addCriterion("IN_CUENTA_EXPIRADA <=", value, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaLike(String value) {
            addCriterion("IN_CUENTA_EXPIRADA like", value, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaNotLike(String value) {
            addCriterion("IN_CUENTA_EXPIRADA not like", value, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaIn(List<String> values) {
            addCriterion("IN_CUENTA_EXPIRADA in", values, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaNotIn(List<String> values) {
            addCriterion("IN_CUENTA_EXPIRADA not in", values, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaBetween(String value1, String value2) {
            addCriterion("IN_CUENTA_EXPIRADA between", value1, value2, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaNotBetween(String value1, String value2) {
            addCriterion("IN_CUENTA_EXPIRADA not between", value1, value2, "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaIsNull() {
            addCriterion("IN_CUENTA_BLOQUEADA is null");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaIsNotNull() {
            addCriterion("IN_CUENTA_BLOQUEADA is not null");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaEqualTo(String value) {
            addCriterion("IN_CUENTA_BLOQUEADA =", value, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaNotEqualTo(String value) {
            addCriterion("IN_CUENTA_BLOQUEADA <>", value, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaGreaterThan(String value) {
            addCriterion("IN_CUENTA_BLOQUEADA >", value, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaGreaterThanOrEqualTo(String value) {
            addCriterion("IN_CUENTA_BLOQUEADA >=", value, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaLessThan(String value) {
            addCriterion("IN_CUENTA_BLOQUEADA <", value, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaLessThanOrEqualTo(String value) {
            addCriterion("IN_CUENTA_BLOQUEADA <=", value, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaLike(String value) {
            addCriterion("IN_CUENTA_BLOQUEADA like", value, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaNotLike(String value) {
            addCriterion("IN_CUENTA_BLOQUEADA not like", value, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaIn(List<String> values) {
            addCriterion("IN_CUENTA_BLOQUEADA in", values, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaNotIn(List<String> values) {
            addCriterion("IN_CUENTA_BLOQUEADA not in", values, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaBetween(String value1, String value2) {
            addCriterion("IN_CUENTA_BLOQUEADA between", value1, value2, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaNotBetween(String value1, String value2) {
            addCriterion("IN_CUENTA_BLOQUEADA not between", value1, value2, "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaIsNull() {
            addCriterion("IN_CREDENCIAL_EXPIRADA is null");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaIsNotNull() {
            addCriterion("IN_CREDENCIAL_EXPIRADA is not null");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaEqualTo(String value) {
            addCriterion("IN_CREDENCIAL_EXPIRADA =", value, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaNotEqualTo(String value) {
            addCriterion("IN_CREDENCIAL_EXPIRADA <>", value, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaGreaterThan(String value) {
            addCriterion("IN_CREDENCIAL_EXPIRADA >", value, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaGreaterThanOrEqualTo(String value) {
            addCriterion("IN_CREDENCIAL_EXPIRADA >=", value, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaLessThan(String value) {
            addCriterion("IN_CREDENCIAL_EXPIRADA <", value, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaLessThanOrEqualTo(String value) {
            addCriterion("IN_CREDENCIAL_EXPIRADA <=", value, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaLike(String value) {
            addCriterion("IN_CREDENCIAL_EXPIRADA like", value, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaNotLike(String value) {
            addCriterion("IN_CREDENCIAL_EXPIRADA not like", value, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaIn(List<String> values) {
            addCriterion("IN_CREDENCIAL_EXPIRADA in", values, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaNotIn(List<String> values) {
            addCriterion("IN_CREDENCIAL_EXPIRADA not in", values, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaBetween(String value1, String value2) {
            addCriterion("IN_CREDENCIAL_EXPIRADA between", value1, value2, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaNotBetween(String value1, String value2) {
            addCriterion("IN_CREDENCIAL_EXPIRADA not between", value1, value2, "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoIsNull() {
            addCriterion("IN_HABILITADO is null");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoIsNotNull() {
            addCriterion("IN_HABILITADO is not null");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoEqualTo(String value) {
            addCriterion("IN_HABILITADO =", value, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoNotEqualTo(String value) {
            addCriterion("IN_HABILITADO <>", value, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoGreaterThan(String value) {
            addCriterion("IN_HABILITADO >", value, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoGreaterThanOrEqualTo(String value) {
            addCriterion("IN_HABILITADO >=", value, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoLessThan(String value) {
            addCriterion("IN_HABILITADO <", value, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoLessThanOrEqualTo(String value) {
            addCriterion("IN_HABILITADO <=", value, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoLike(String value) {
            addCriterion("IN_HABILITADO like", value, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoNotLike(String value) {
            addCriterion("IN_HABILITADO not like", value, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoIn(List<String> values) {
            addCriterion("IN_HABILITADO in", values, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoNotIn(List<String> values) {
            addCriterion("IN_HABILITADO not in", values, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoBetween(String value1, String value2) {
            addCriterion("IN_HABILITADO between", value1, value2, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoNotBetween(String value1, String value2) {
            addCriterion("IN_HABILITADO not between", value1, value2, "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andDesParametro1IsNull() {
            addCriterion("DES_PARAMETRO1 is null");
            return (Criteria) this;
        }

        public Criteria andDesParametro1IsNotNull() {
            addCriterion("DES_PARAMETRO1 is not null");
            return (Criteria) this;
        }

        public Criteria andDesParametro1EqualTo(String value) {
            addCriterion("DES_PARAMETRO1 =", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1NotEqualTo(String value) {
            addCriterion("DES_PARAMETRO1 <>", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1GreaterThan(String value) {
            addCriterion("DES_PARAMETRO1 >", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1GreaterThanOrEqualTo(String value) {
            addCriterion("DES_PARAMETRO1 >=", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1LessThan(String value) {
            addCriterion("DES_PARAMETRO1 <", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1LessThanOrEqualTo(String value) {
            addCriterion("DES_PARAMETRO1 <=", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1Like(String value) {
            addCriterion("DES_PARAMETRO1 like", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1NotLike(String value) {
            addCriterion("DES_PARAMETRO1 not like", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1In(List<String> values) {
            addCriterion("DES_PARAMETRO1 in", values, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1NotIn(List<String> values) {
            addCriterion("DES_PARAMETRO1 not in", values, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1Between(String value1, String value2) {
            addCriterion("DES_PARAMETRO1 between", value1, value2, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1NotBetween(String value1, String value2) {
            addCriterion("DES_PARAMETRO1 not between", value1, value2, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxIsNull() {
            addCriterion("DES_RUTA_SIGNPFX is null");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxIsNotNull() {
            addCriterion("DES_RUTA_SIGNPFX is not null");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxEqualTo(String value) {
            addCriterion("DES_RUTA_SIGNPFX =", value, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxNotEqualTo(String value) {
            addCriterion("DES_RUTA_SIGNPFX <>", value, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxGreaterThan(String value) {
            addCriterion("DES_RUTA_SIGNPFX >", value, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxGreaterThanOrEqualTo(String value) {
            addCriterion("DES_RUTA_SIGNPFX >=", value, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxLessThan(String value) {
            addCriterion("DES_RUTA_SIGNPFX <", value, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxLessThanOrEqualTo(String value) {
            addCriterion("DES_RUTA_SIGNPFX <=", value, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxLike(String value) {
            addCriterion("DES_RUTA_SIGNPFX like", value, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxNotLike(String value) {
            addCriterion("DES_RUTA_SIGNPFX not like", value, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxIn(List<String> values) {
            addCriterion("DES_RUTA_SIGNPFX in", values, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxNotIn(List<String> values) {
            addCriterion("DES_RUTA_SIGNPFX not in", values, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxBetween(String value1, String value2) {
            addCriterion("DES_RUTA_SIGNPFX between", value1, value2, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxNotBetween(String value1, String value2) {
            addCriterion("DES_RUTA_SIGNPFX not between", value1, value2, "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageIsNull() {
            addCriterion("DES_RUTA_SIGNIMAGE is null");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageIsNotNull() {
            addCriterion("DES_RUTA_SIGNIMAGE is not null");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageEqualTo(String value) {
            addCriterion("DES_RUTA_SIGNIMAGE =", value, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageNotEqualTo(String value) {
            addCriterion("DES_RUTA_SIGNIMAGE <>", value, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageGreaterThan(String value) {
            addCriterion("DES_RUTA_SIGNIMAGE >", value, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageGreaterThanOrEqualTo(String value) {
            addCriterion("DES_RUTA_SIGNIMAGE >=", value, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageLessThan(String value) {
            addCriterion("DES_RUTA_SIGNIMAGE <", value, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageLessThanOrEqualTo(String value) {
            addCriterion("DES_RUTA_SIGNIMAGE <=", value, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageLike(String value) {
            addCriterion("DES_RUTA_SIGNIMAGE like", value, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageNotLike(String value) {
            addCriterion("DES_RUTA_SIGNIMAGE not like", value, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageIn(List<String> values) {
            addCriterion("DES_RUTA_SIGNIMAGE in", values, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageNotIn(List<String> values) {
            addCriterion("DES_RUTA_SIGNIMAGE not in", values, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageBetween(String value1, String value2) {
            addCriterion("DES_RUTA_SIGNIMAGE between", value1, value2, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageNotBetween(String value1, String value2) {
            addCriterion("DES_RUTA_SIGNIMAGE not between", value1, value2, "desRutaSignimage");
            return (Criteria) this;
        }

        public Criteria andDesLoginUserLikeInsensitive(String value) {
            addCriterion("upper(DES_LOGIN_USER) like", value.toUpperCase(), "desLoginUser");
            return (Criteria) this;
        }

        public Criteria andClvClaveUserLikeInsensitive(String value) {
            addCriterion("upper(CLV_CLAVE_USER) like", value.toUpperCase(), "clvClaveUser");
            return (Criteria) this;
        }

        public Criteria andDesUsuRegistraLikeInsensitive(String value) {
            addCriterion("upper(DES_USU_REGISTRA) like", value.toUpperCase(), "desUsuRegistra");
            return (Criteria) this;
        }

        public Criteria andDesUsuModificaLikeInsensitive(String value) {
            addCriterion("upper(DES_USU_MODIFICA) like", value.toUpperCase(), "desUsuModifica");
            return (Criteria) this;
        }

        public Criteria andDesIpRegistraLikeInsensitive(String value) {
            addCriterion("upper(DES_IP_REGISTRA) like", value.toUpperCase(), "desIpRegistra");
            return (Criteria) this;
        }

        public Criteria andDesIpModificaLikeInsensitive(String value) {
            addCriterion("upper(DES_IP_MODIFICA) like", value.toUpperCase(), "desIpModifica");
            return (Criteria) this;
        }

        public Criteria andInCuentaExpiradaLikeInsensitive(String value) {
            addCriterion("upper(IN_CUENTA_EXPIRADA) like", value.toUpperCase(), "inCuentaExpirada");
            return (Criteria) this;
        }

        public Criteria andInCuentaBloqueadaLikeInsensitive(String value) {
            addCriterion("upper(IN_CUENTA_BLOQUEADA) like", value.toUpperCase(), "inCuentaBloqueada");
            return (Criteria) this;
        }

        public Criteria andInCredencialExpiradaLikeInsensitive(String value) {
            addCriterion("upper(IN_CREDENCIAL_EXPIRADA) like", value.toUpperCase(), "inCredencialExpirada");
            return (Criteria) this;
        }

        public Criteria andInHabilitadoLikeInsensitive(String value) {
            addCriterion("upper(IN_HABILITADO) like", value.toUpperCase(), "inHabilitado");
            return (Criteria) this;
        }

        public Criteria andDesParametro1LikeInsensitive(String value) {
            addCriterion("upper(DES_PARAMETRO1) like", value.toUpperCase(), "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignpfxLikeInsensitive(String value) {
            addCriterion("upper(DES_RUTA_SIGNPFX) like", value.toUpperCase(), "desRutaSignpfx");
            return (Criteria) this;
        }

        public Criteria andDesRutaSignimageLikeInsensitive(String value) {
            addCriterion("upper(DES_RUTA_SIGNIMAGE) like", value.toUpperCase(), "desRutaSignimage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ADMCUSER
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 04 11:42:45 COT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ADMCUSER
     *
     * @mbggenerated Mon Jan 04 11:42:45 COT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}